// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public final class A2A {
  private A2A() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      A2A.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Part_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Part_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_FilePart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_FilePart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_DataPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_DataPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Artifact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PushNotificationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PushNotificationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthenticationInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentInterface_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentInterface_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentProvider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentProvider_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCapabilities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentSkill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentSkill_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskPushNotificationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_StringList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_StringList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Security_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Security_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Security_SchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Security_SchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_APIKeySecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_APIKeySecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OAuth2SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OAuthFlows_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OAuthFlows_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ImplicitOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PasswordOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PasswordOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_CancelTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_CancelTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetAgentCardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetAgentCardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ta2a.proto\022\006a2a.v1\032\034google/api/annotati" +
      "ons.proto\032\027google/api/client.proto\032\037goog" +
      "le/api/field_behavior.proto\032\033google/prot" +
      "obuf/empty.proto\032\034google/protobuf/struct" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "\336\001\n\030SendMessageConfiguration\0222\n\025accepted" +
      "_output_modes\030\001 \003(\tR\023acceptedOutputModes" +
      "\022K\n\021push_notification\030\002 \001(\0132\036.a2a.v1.Pus" +
      "hNotificationConfigR\020pushNotification\022%\n" +
      "\016history_length\030\003 \001(\005R\rhistoryLength\022\032\n\010" +
      "blocking\030\004 \001(\010R\010blocking\"\361\001\n\004Task\022\016\n\002id\030" +
      "\001 \001(\tR\002id\022\035\n\ncontext_id\030\002 \001(\tR\tcontextId" +
      "\022*\n\006status\030\003 \001(\0132\022.a2a.v1.TaskStatusR\006st" +
      "atus\022.\n\tartifacts\030\004 \003(\0132\020.a2a.v1.Artifac" +
      "tR\tartifacts\022)\n\007history\030\005 \003(\0132\017.a2a.v1.M" +
      "essageR\007history\0223\n\010metadata\030\006 \001(\0132\027.goog" +
      "le.protobuf.StructR\010metadata\"\231\001\n\nTaskSta" +
      "tus\022\'\n\005state\030\001 \001(\0162\021.a2a.v1.TaskStateR\005s" +
      "tate\022(\n\006update\030\002 \001(\0132\017.a2a.v1.MessageR\007m" +
      "essage\0228\n\ttimestamp\030\003 \001(\0132\032.google.proto" +
      "buf.TimestampR\ttimestamp\"t\n\004Part\022\024\n\004text" +
      "\030\001 \001(\tH\000R\004text\022&\n\004file\030\002 \001(\0132\020.a2a.v1.Fi" +
      "lePartH\000R\004file\022&\n\004data\030\003 \001(\0132\020.a2a.v1.Da" +
      "taPartH\000R\004dataB\006\n\004part\"\177\n\010FilePart\022$\n\rfi" +
      "le_with_uri\030\001 \001(\tH\000R\013fileWithUri\022(\n\017file" +
      "_with_bytes\030\002 \001(\014H\000R\rfileWithBytes\022\033\n\tmi" +
      "me_type\030\003 \001(\tR\010mimeTypeB\006\n\004file\"7\n\010DataP" +
      "art\022+\n\004data\030\001 \001(\0132\027.google.protobuf.Stru" +
      "ctR\004data\"\377\001\n\007Message\022\035\n\nmessage_id\030\001 \001(\t" +
      "R\tmessageId\022\035\n\ncontext_id\030\002 \001(\tR\tcontext" +
      "Id\022\027\n\007task_id\030\003 \001(\tR\006taskId\022 \n\004role\030\004 \001(" +
      "\0162\014.a2a.v1.RoleR\004role\022&\n\007content\030\005 \003(\0132\014" +
      ".a2a.v1.PartR\007content\0223\n\010metadata\030\006 \001(\0132" +
      "\027.google.protobuf.StructR\010metadata\022\036\n\nex" +
      "tensions\030\007 \003(\tR\nextensions\"\332\001\n\010Artifact\022" +
      "\037\n\013artifact_id\030\001 \001(\tR\nartifactId\022\022\n\004name" +
      "\030\003 \001(\tR\004name\022 \n\013description\030\004 \001(\tR\013descr" +
      "iption\022\"\n\005parts\030\005 \003(\0132\014.a2a.v1.PartR\005par" +
      "ts\0223\n\010metadata\030\006 \001(\0132\027.google.protobuf.S" +
      "tructR\010metadata\022\036\n\nextensions\030\007 \003(\tR\next" +
      "ensions\"\306\001\n\025TaskStatusUpdateEvent\022\027\n\007tas" +
      "k_id\030\001 \001(\tR\006taskId\022\035\n\ncontext_id\030\002 \001(\tR\t" +
      "contextId\022*\n\006status\030\003 \001(\0132\022.a2a.v1.TaskS" +
      "tatusR\006status\022\024\n\005final\030\004 \001(\010R\005final\0223\n\010m" +
      "etadata\030\005 \001(\0132\027.google.protobuf.StructR\010" +
      "metadata\"\353\001\n\027TaskArtifactUpdateEvent\022\027\n\007" +
      "task_id\030\001 \001(\tR\006taskId\022\035\n\ncontext_id\030\002 \001(" +
      "\tR\tcontextId\022,\n\010artifact\030\003 \001(\0132\020.a2a.v1." +
      "ArtifactR\010artifact\022\026\n\006append\030\004 \001(\010R\006appe" +
      "nd\022\035\n\nlast_chunk\030\005 \001(\010R\tlastChunk\0223\n\010met" +
      "adata\030\006 \001(\0132\027.google.protobuf.StructR\010me" +
      "tadata\"\224\001\n\026PushNotificationConfig\022\016\n\002id\030" +
      "\001 \001(\tR\002id\022\020\n\003url\030\002 \001(\tR\003url\022\024\n\005token\030\003 \001" +
      "(\tR\005token\022B\n\016authentication\030\004 \001(\0132\032.a2a." +
      "v1.AuthenticationInfoR\016authentication\"P\n" +
      "\022AuthenticationInfo\022\030\n\007schemes\030\001 \003(\tR\007sc" +
      "hemes\022 \n\013credentials\030\002 \001(\tR\013credentials\"" +
      "@\n\016AgentInterface\022\020\n\003url\030\001 \001(\tR\003url\022\034\n\tt" +
      "ransport\030\002 \001(\tR\ttransport\"\361\006\n\tAgentCard\022" +
      ")\n\020protocol_version\030\020 \001(\tR\017protocolVersi" +
      "on\022\022\n\004name\030\001 \001(\tR\004name\022 \n\013description\030\002 " +
      "\001(\tR\013description\022\020\n\003url\030\003 \001(\tR\003url\022/\n\023pr" +
      "eferred_transport\030\016 \001(\tR\022preferredTransp" +
      "ort\022K\n\025additional_interfaces\030\017 \003(\0132\026.a2a" +
      ".v1.AgentInterfaceR\024additionalInterfaces" +
      "\0221\n\010provider\030\004 \001(\0132\025.a2a.v1.AgentProvide" +
      "rR\010provider\022\030\n\007version\030\005 \001(\tR\007version\022+\n" +
      "\021documentation_url\030\006 \001(\tR\020documentationU" +
      "rl\022=\n\014capabilities\030\007 \001(\0132\031.a2a.v1.AgentC" +
      "apabilitiesR\014capabilities\022Q\n\020security_sc" +
      "hemes\030\010 \003(\0132&.a2a.v1.AgentCard.SecurityS" +
      "chemesEntryR\017securitySchemes\022,\n\010security" +
      "\030\t \003(\0132\020.a2a.v1.SecurityR\010security\022.\n\023de" +
      "fault_input_modes\030\n \003(\tR\021defaultInputMod" +
      "es\0220\n\024default_output_modes\030\013 \003(\tR\022defaul" +
      "tOutputModes\022*\n\006skills\030\014 \003(\0132\022.a2a.v1.Ag" +
      "entSkillR\006skills\022O\n$supports_authenticat" +
      "ed_extended_card\030\r \001(\010R!supportsAuthenti" +
      "catedExtendedCard\032Z\n\024SecuritySchemesEntr" +
      "y\022\020\n\003key\030\001 \001(\tR\003key\022,\n\005value\030\002 \001(\0132\026.a2a" +
      ".v1.SecuritySchemeR\005value:\0028\001\"E\n\rAgentPr" +
      "ovider\022\020\n\003url\030\001 \001(\tR\003url\022\"\n\014organization" +
      "\030\002 \001(\tR\014organization\"\230\001\n\021AgentCapabiliti" +
      "es\022\034\n\tstreaming\030\001 \001(\010R\tstreaming\022-\n\022push" +
      "_notifications\030\002 \001(\010R\021pushNotifications\022" +
      "6\n\nextensions\030\003 \003(\0132\026.a2a.v1.AgentExtens" +
      "ionR\nextensions\"\221\001\n\016AgentExtension\022\020\n\003ur" +
      "i\030\001 \001(\tR\003uri\022 \n\013description\030\002 \001(\tR\013descr" +
      "iption\022\032\n\010required\030\003 \001(\010R\010required\022/\n\006pa" +
      "rams\030\004 \001(\0132\027.google.protobuf.StructR\006par" +
      "ams\"\306\001\n\nAgentSkill\022\016\n\002id\030\001 \001(\tR\002id\022\022\n\004na" +
      "me\030\002 \001(\tR\004name\022 \n\013description\030\003 \001(\tR\013des" +
      "cription\022\022\n\004tags\030\004 \003(\tR\004tags\022\032\n\010examples" +
      "\030\005 \003(\tR\010examples\022\037\n\013input_modes\030\006 \003(\tR\ni" +
      "nputModes\022!\n\014output_modes\030\007 \003(\tR\013outputM" +
      "odes\"\212\001\n\032TaskPushNotificationConfig\022\022\n\004n" +
      "ame\030\001 \001(\tR\004name\022X\n\030push_notification_con" +
      "fig\030\002 \001(\0132\036.a2a.v1.PushNotificationConfi" +
      "gR\026pushNotificationConfig\" \n\nStringList\022" +
      "\022\n\004list\030\001 \003(\tR\004list\"\223\001\n\010Security\0227\n\007sche" +
      "mes\030\001 \003(\0132\035.a2a.v1.Security.SchemesEntry" +
      "R\007schemes\032N\n\014SchemesEntry\022\020\n\003key\030\001 \001(\tR\003" +
      "key\022(\n\005value\030\002 \001(\0132\022.a2a.v1.StringListR\005" +
      "value:\0028\001\"\221\003\n\016SecurityScheme\022U\n\027api_key_" +
      "security_scheme\030\001 \001(\0132\034.a2a.v1.APIKeySec" +
      "uritySchemeH\000R\024apiKeySecurityScheme\022[\n\031h" +
      "ttp_auth_security_scheme\030\002 \001(\0132\036.a2a.v1." +
      "HTTPAuthSecuritySchemeH\000R\026httpAuthSecuri" +
      "tyScheme\022T\n\026oauth2_security_scheme\030\003 \001(\013" +
      "2\034.a2a.v1.OAuth2SecuritySchemeH\000R\024oauth2" +
      "SecurityScheme\022k\n\037open_id_connect_securi" +
      "ty_scheme\030\004 \001(\0132#.a2a.v1.OpenIdConnectSe" +
      "curitySchemeH\000R\033openIdConnectSecuritySch" +
      "emeB\010\n\006scheme\"h\n\024APIKeySecurityScheme\022 \n" +
      "\013description\030\001 \001(\tR\013description\022\032\n\010locat" +
      "ion\030\002 \001(\tR\010location\022\022\n\004name\030\003 \001(\tR\004name\"" +
      "w\n\026HTTPAuthSecurityScheme\022 \n\013description" +
      "\030\001 \001(\tR\013description\022\026\n\006scheme\030\002 \001(\tR\006sch" +
      "eme\022#\n\rbearer_format\030\003 \001(\tR\014bearerFormat" +
      "\"b\n\024OAuth2SecurityScheme\022 \n\013description\030" +
      "\001 \001(\tR\013description\022(\n\005flows\030\002 \001(\0132\022.a2a." +
      "v1.OAuthFlowsR\005flows\"n\n\033OpenIdConnectSec" +
      "urityScheme\022 \n\013description\030\001 \001(\tR\013descri" +
      "ption\022-\n\023open_id_connect_url\030\002 \001(\tR\020open" +
      "IdConnectUrl\"\260\002\n\nOAuthFlows\022S\n\022authoriza" +
      "tion_code\030\001 \001(\0132\".a2a.v1.AuthorizationCo" +
      "deOAuthFlowH\000R\021authorizationCode\022S\n\022clie" +
      "nt_credentials\030\002 \001(\0132\".a2a.v1.ClientCred" +
      "entialsOAuthFlowH\000R\021clientCredentials\0227\n" +
      "\010implicit\030\003 \001(\0132\031.a2a.v1.ImplicitOAuthFl" +
      "owH\000R\010implicit\0227\n\010password\030\004 \001(\0132\031.a2a.v" +
      "1.PasswordOAuthFlowH\000R\010passwordB\006\n\004flow\"" +
      "\212\002\n\032AuthorizationCodeOAuthFlow\022+\n\021author" +
      "ization_url\030\001 \001(\tR\020authorizationUrl\022\033\n\tt" +
      "oken_url\030\002 \001(\tR\010tokenUrl\022\037\n\013refresh_url\030" +
      "\003 \001(\tR\nrefreshUrl\022F\n\006scopes\030\004 \003(\0132..a2a." +
      "v1.AuthorizationCodeOAuthFlow.ScopesEntr" +
      "yR\006scopes\0329\n\013ScopesEntry\022\020\n\003key\030\001 \001(\tR\003k" +
      "ey\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"\335\001\n\032ClientC" +
      "redentialsOAuthFlow\022\033\n\ttoken_url\030\001 \001(\tR\010" +
      "tokenUrl\022\037\n\013refresh_url\030\002 \001(\tR\nrefreshUr" +
      "l\022F\n\006scopes\030\003 \003(\0132..a2a.v1.ClientCredent" +
      "ialsOAuthFlow.ScopesEntryR\006scopes\0329\n\013Sco" +
      "pesEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(" +
      "\tR\005value:\0028\001\"\333\001\n\021ImplicitOAuthFlow\022+\n\021au" +
      "thorization_url\030\001 \001(\tR\020authorizationUrl\022" +
      "\037\n\013refresh_url\030\002 \001(\tR\nrefreshUrl\022=\n\006scop" +
      "es\030\003 \003(\0132%.a2a.v1.ImplicitOAuthFlow.Scop" +
      "esEntryR\006scopes\0329\n\013ScopesEntry\022\020\n\003key\030\001 " +
      "\001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\"\313\001\n\021P" +
      "asswordOAuthFlow\022\033\n\ttoken_url\030\001 \001(\tR\010tok" +
      "enUrl\022\037\n\013refresh_url\030\002 \001(\tR\nrefreshUrl\022=" +
      "\n\006scopes\030\003 \003(\0132%.a2a.v1.PasswordOAuthFlo" +
      "w.ScopesEntryR\006scopes\0329\n\013ScopesEntry\022\020\n\003" +
      "key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001" +
      "\"\301\001\n\022SendMessageRequest\022.\n\007request\030\001 \001(\013" +
      "2\017.a2a.v1.MessageB\003\340A\002R\007request\022F\n\rconfi" +
      "guration\030\002 \001(\0132 .a2a.v1.SendMessageConfi" +
      "gurationR\rconfiguration\0223\n\010metadata\030\003 \001(" +
      "\0132\027.google.protobuf.StructR\010metadata\"P\n\016" +
      "GetTaskRequest\022\027\n\004name\030\001 \001(\tB\003\340A\002R\004name\022" +
      "%\n\016history_length\030\002 \001(\005R\rhistoryLength\"\'" +
      "\n\021CancelTaskRequest\022\022\n\004name\030\001 \001(\tR\004name\"" +
      ":\n$GetTaskPushNotificationConfigRequest\022" +
      "\022\n\004name\030\001 \001(\tR\004name\"=\n\'DeleteTaskPushNot" +
      "ificationConfigRequest\022\022\n\004name\030\001 \001(\tR\004na" +
      "me\"\251\001\n\'CreateTaskPushNotificationConfigR" +
      "equest\022\033\n\006parent\030\001 \001(\tB\003\340A\002R\006parent\022 \n\tc" +
      "onfig_id\030\002 \001(\tB\003\340A\002R\010configId\022?\n\006config\030" +
      "\003 \001(\0132\".a2a.v1.TaskPushNotificationConfi" +
      "gB\003\340A\002R\006config\"-\n\027TaskSubscriptionReques" +
      "t\022\022\n\004name\030\001 \001(\tR\004name\"{\n%ListTaskPushNot" +
      "ificationConfigRequest\022\026\n\006parent\030\001 \001(\tR\006" +
      "parent\022\033\n\tpage_size\030\002 \001(\005R\010pageSize\022\035\n\np" +
      "age_token\030\003 \001(\tR\tpageToken\"\025\n\023GetAgentCa" +
      "rdRequest\"m\n\023SendMessageResponse\022\"\n\004task" +
      "\030\001 \001(\0132\014.a2a.v1.TaskH\000R\004task\022\'\n\003msg\030\002 \001(" +
      "\0132\017.a2a.v1.MessageH\000R\007messageB\t\n\007payload" +
      "\"\372\001\n\016StreamResponse\022\"\n\004task\030\001 \001(\0132\014.a2a." +
      "v1.TaskH\000R\004task\022\'\n\003msg\030\002 \001(\0132\017.a2a.v1.Me" +
      "ssageH\000R\007message\022D\n\rstatus_update\030\003 \001(\0132" +
      "\035.a2a.v1.TaskStatusUpdateEventH\000R\014status" +
      "Update\022J\n\017artifact_update\030\004 \001(\0132\037.a2a.v1" +
      ".TaskArtifactUpdateEventH\000R\016artifactUpda" +
      "teB\t\n\007payload\"\216\001\n&ListTaskPushNotificati" +
      "onConfigResponse\022<\n\007configs\030\001 \003(\0132\".a2a." +
      "v1.TaskPushNotificationConfigR\007configs\022&" +
      "\n\017next_page_token\030\002 \001(\tR\rnextPageToken*\372" +
      "\001\n\tTaskState\022\032\n\026TASK_STATE_UNSPECIFIED\020\000" +
      "\022\030\n\024TASK_STATE_SUBMITTED\020\001\022\026\n\022TASK_STATE" +
      "_WORKING\020\002\022\030\n\024TASK_STATE_COMPLETED\020\003\022\025\n\021" +
      "TASK_STATE_FAILED\020\004\022\030\n\024TASK_STATE_CANCEL" +
      "LED\020\005\022\035\n\031TASK_STATE_INPUT_REQUIRED\020\006\022\027\n\023" +
      "TASK_STATE_REJECTED\020\007\022\034\n\030TASK_STATE_AUTH" +
      "_REQUIRED\020\010*;\n\004Role\022\024\n\020ROLE_UNSPECIFIED\020" +
      "\000\022\r\n\tROLE_USER\020\001\022\016\n\nROLE_AGENT\020\0022\272\n\n\nA2A" +
      "Service\022c\n\013SendMessage\022\032.a2a.v1.SendMess" +
      "ageRequest\032\033.a2a.v1.SendMessageResponse\"" +
      "\033\202\323\344\223\002\025\"\020/v1/message:send:\001*\022k\n\024SendStre" +
      "amingMessage\022\032.a2a.v1.SendMessageRequest" +
      "\032\026.a2a.v1.StreamResponse\"\035\202\323\344\223\002\027\"\022/v1/me" +
      "ssage:stream:\001*0\001\022R\n\007GetTask\022\026.a2a.v1.Ge" +
      "tTaskRequest\032\014.a2a.v1.Task\"!\332A\004name\202\323\344\223\002" +
      "\024\022\022/v1/{name=tasks/*}\022[\n\nCancelTask\022\031.a2" +
      "a.v1.CancelTaskRequest\032\014.a2a.v1.Task\"$\202\323" +
      "\344\223\002\036\"\031/v1/{name=tasks/*}:cancel:\001*\022s\n\020Ta" +
      "skSubscription\022\037.a2a.v1.TaskSubscription" +
      "Request\032\026.a2a.v1.StreamResponse\"$\202\323\344\223\002\036\022" +
      "\034/v1/{name=tasks/*}:subscribe0\001\022\304\001\n Crea" +
      "teTaskPushNotificationConfig\022/.a2a.v1.Cr" +
      "eateTaskPushNotificationConfigRequest\032\"." +
      "a2a.v1.TaskPushNotificationConfig\"K\332A\rpa" +
      "rent,config\202\323\344\223\0025\"+/v1/{parent=task/*/pu" +
      "shNotificationConfigs}:\006config\022\256\001\n\035GetTa" +
      "skPushNotificationConfig\022,.a2a.v1.GetTas" +
      "kPushNotificationConfigRequest\032\".a2a.v1." +
      "TaskPushNotificationConfig\";\332A\004name\202\323\344\223\002" +
      ".\022,/v1/{name=tasks/*/pushNotificationCon" +
      "figs/*}\022\276\001\n\036ListTaskPushNotificationConf" +
      "ig\022-.a2a.v1.ListTaskPushNotificationConf" +
      "igRequest\032..a2a.v1.ListTaskPushNotificat" +
      "ionConfigResponse\"=\332A\006parent\202\323\344\223\002.\022,/v1/" +
      "{parent=tasks/*}/pushNotificationConfigs" +
      "\022P\n\014GetAgentCard\022\033.a2a.v1.GetAgentCardRe" +
      "quest\032\021.a2a.v1.AgentCard\"\020\202\323\344\223\002\n\022\010/v1/ca" +
      "rd\022\250\001\n DeleteTaskPushNotificationConfig\022" +
      "/.a2a.v1.DeleteTaskPushNotificationConfi" +
      "gRequest\032\026.google.protobuf.Empty\";\332A\004nam" +
      "e\202\323\344\223\002.*,/v1/{name=tasks/*/pushNotificat" +
      "ionConfigs/*}B7\n\013io.a2a.grpcB\003A2AP\001Z\030goo" +
      "gle.golang.org/a2a/v1\252\002\006A2a.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_a2a_v1_SendMessageConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageConfiguration_descriptor,
        new java.lang.String[] { "AcceptedOutputModes", "PushNotification", "HistoryLength", "Blocking", });
    internal_static_a2a_v1_Task_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_a2a_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Task_descriptor,
        new java.lang.String[] { "Id", "ContextId", "Status", "Artifacts", "History", "Metadata", });
    internal_static_a2a_v1_TaskStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_a2a_v1_TaskStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskStatus_descriptor,
        new java.lang.String[] { "State", "Update", "Timestamp", });
    internal_static_a2a_v1_Part_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_a2a_v1_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Part_descriptor,
        new java.lang.String[] { "Text", "File", "Data", "Part", });
    internal_static_a2a_v1_FilePart_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_a2a_v1_FilePart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_FilePart_descriptor,
        new java.lang.String[] { "FileWithUri", "FileWithBytes", "MimeType", "File", });
    internal_static_a2a_v1_DataPart_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_a2a_v1_DataPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_DataPart_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_a2a_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_a2a_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Message_descriptor,
        new java.lang.String[] { "MessageId", "ContextId", "TaskId", "Role", "Content", "Metadata", "Extensions", });
    internal_static_a2a_v1_Artifact_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_a2a_v1_Artifact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Artifact_descriptor,
        new java.lang.String[] { "ArtifactId", "Name", "Description", "Parts", "Metadata", "Extensions", });
    internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Status", "Final", "Metadata", });
    internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Artifact", "Append", "LastChunk", "Metadata", });
    internal_static_a2a_v1_PushNotificationConfig_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_a2a_v1_PushNotificationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PushNotificationConfig_descriptor,
        new java.lang.String[] { "Id", "Url", "Token", "Authentication", });
    internal_static_a2a_v1_AuthenticationInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthenticationInfo_descriptor,
        new java.lang.String[] { "Schemes", "Credentials", });
    internal_static_a2a_v1_AgentInterface_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_a2a_v1_AgentInterface_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentInterface_descriptor,
        new java.lang.String[] { "Url", "Transport", });
    internal_static_a2a_v1_AgentCard_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_a2a_v1_AgentCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCard_descriptor,
        new java.lang.String[] { "ProtocolVersion", "Name", "Description", "Url", "PreferredTransport", "AdditionalInterfaces", "Provider", "Version", "DocumentationUrl", "Capabilities", "SecuritySchemes", "Security", "DefaultInputModes", "DefaultOutputModes", "Skills", "SupportsAuthenticatedExtendedCard", });
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor =
      internal_static_a2a_v1_AgentCard_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_AgentProvider_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_a2a_v1_AgentProvider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentProvider_descriptor,
        new java.lang.String[] { "Url", "Organization", });
    internal_static_a2a_v1_AgentCapabilities_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCapabilities_descriptor,
        new java.lang.String[] { "Streaming", "PushNotifications", "Extensions", });
    internal_static_a2a_v1_AgentExtension_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_a2a_v1_AgentExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentExtension_descriptor,
        new java.lang.String[] { "Uri", "Description", "Required", "Params", });
    internal_static_a2a_v1_AgentSkill_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_a2a_v1_AgentSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentSkill_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Tags", "Examples", "InputModes", "OutputModes", });
    internal_static_a2a_v1_TaskPushNotificationConfig_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskPushNotificationConfig_descriptor,
        new java.lang.String[] { "Name", "PushNotificationConfig", });
    internal_static_a2a_v1_StringList_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_a2a_v1_StringList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_StringList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_a2a_v1_Security_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_a2a_v1_Security_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Security_descriptor,
        new java.lang.String[] { "Schemes", });
    internal_static_a2a_v1_Security_SchemesEntry_descriptor =
      internal_static_a2a_v1_Security_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_Security_SchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Security_SchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_SecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_a2a_v1_SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SecurityScheme_descriptor,
        new java.lang.String[] { "ApiKeySecurityScheme", "HttpAuthSecurityScheme", "Oauth2SecurityScheme", "OpenIdConnectSecurityScheme", "Scheme", });
    internal_static_a2a_v1_APIKeySecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_a2a_v1_APIKeySecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_APIKeySecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Location", "Name", });
    internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Scheme", "BearerFormat", });
    internal_static_a2a_v1_OAuth2SecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OAuth2SecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Flows", });
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "OpenIdConnectUrl", });
    internal_static_a2a_v1_OAuthFlows_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_a2a_v1_OAuthFlows_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OAuthFlows_descriptor,
        new java.lang.String[] { "AuthorizationCode", "ClientCredentials", "Implicit", "Password", "Flow", });
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_ImplicitOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ImplicitOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_ImplicitOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_PasswordOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_a2a_v1_PasswordOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PasswordOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_PasswordOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageRequest_descriptor,
        new java.lang.String[] { "Request", "Configuration", "Metadata", });
    internal_static_a2a_v1_GetTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_a2a_v1_GetTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetTaskRequest_descriptor,
        new java.lang.String[] { "Name", "HistoryLength", });
    internal_static_a2a_v1_CancelTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_a2a_v1_CancelTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_CancelTaskRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Parent", "ConfigId", "Config", });
    internal_static_a2a_v1_TaskSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_a2a_v1_TaskSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskSubscriptionRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_a2a_v1_GetAgentCardRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_a2a_v1_GetAgentCardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetAgentCardRequest_descriptor,
        new java.lang.String[] { });
    internal_static_a2a_v1_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageResponse_descriptor,
        new java.lang.String[] { "Task", "Msg", "Payload", });
    internal_static_a2a_v1_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_a2a_v1_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_StreamResponse_descriptor,
        new java.lang.String[] { "Task", "Msg", "StatusUpdate", "ArtifactUpdate", "Payload", });
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor,
        new java.lang.String[] { "Configs", "NextPageToken", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
