// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface GetTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.GetTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name=tasks/{id}
   * </pre>
   *
   * <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name=tasks/{id}
   * </pre>
   *
   * <code>string name = 1 [json_name = "name", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 history_length = 2 [json_name = "historyLength"];</code>
   * @return The historyLength.
   */
  int getHistoryLength();
}
