// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface OAuth2SecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.OAuth2SecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   * @return Whether the flows field is set.
   */
  boolean hasFlows();
  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   * @return The flows.
   */
  io.a2a.grpc.OAuthFlows getFlows();
  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   */
  io.a2a.grpc.OAuthFlowsOrBuilder getFlowsOrBuilder();
}
