// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * Protobuf type {@code a2a.v1.OAuth2SecurityScheme}
 */
@com.google.protobuf.Generated
public final class OAuth2SecurityScheme extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.OAuth2SecurityScheme)
    OAuth2SecuritySchemeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      OAuth2SecurityScheme.class.getName());
  }
  // Use OAuth2SecurityScheme.newBuilder() to construct.
  private OAuth2SecurityScheme(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OAuth2SecurityScheme() {
    description_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_OAuth2SecurityScheme_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.OAuth2SecurityScheme.class, io.a2a.grpc.OAuth2SecurityScheme.Builder.class);
  }

  private int bitField0_;
  public static final int DESCRIPTION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Description of this security scheme.
   * </pre>
   *
   * <code>string description = 1 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLOWS_FIELD_NUMBER = 2;
  private io.a2a.grpc.OAuthFlows flows_;
  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   * @return Whether the flows field is set.
   */
  @java.lang.Override
  public boolean hasFlows() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   * @return The flows.
   */
  @java.lang.Override
  public io.a2a.grpc.OAuthFlows getFlows() {
    return flows_ == null ? io.a2a.grpc.OAuthFlows.getDefaultInstance() : flows_;
  }
  /**
   * <pre>
   * An object containing configuration information for the flow types supported
   * </pre>
   *
   * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.OAuthFlowsOrBuilder getFlowsOrBuilder() {
    return flows_ == null ? io.a2a.grpc.OAuthFlows.getDefaultInstance() : flows_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, description_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getFlows());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, description_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFlows());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.OAuth2SecurityScheme)) {
      return super.equals(obj);
    }
    io.a2a.grpc.OAuth2SecurityScheme other = (io.a2a.grpc.OAuth2SecurityScheme) obj;

    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (hasFlows() != other.hasFlows()) return false;
    if (hasFlows()) {
      if (!getFlows()
          .equals(other.getFlows())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    if (hasFlows()) {
      hash = (37 * hash) + FLOWS_FIELD_NUMBER;
      hash = (53 * hash) + getFlows().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.OAuth2SecurityScheme parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.OAuth2SecurityScheme parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.OAuth2SecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.OAuth2SecurityScheme prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code a2a.v1.OAuth2SecurityScheme}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.OAuth2SecurityScheme)
      io.a2a.grpc.OAuth2SecuritySchemeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_OAuth2SecurityScheme_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.OAuth2SecurityScheme.class, io.a2a.grpc.OAuth2SecurityScheme.Builder.class);
    }

    // Construct using io.a2a.grpc.OAuth2SecurityScheme.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFlowsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      description_ = "";
      flows_ = null;
      if (flowsBuilder_ != null) {
        flowsBuilder_.dispose();
        flowsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_OAuth2SecurityScheme_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.OAuth2SecurityScheme getDefaultInstanceForType() {
      return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.OAuth2SecurityScheme build() {
      io.a2a.grpc.OAuth2SecurityScheme result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.OAuth2SecurityScheme buildPartial() {
      io.a2a.grpc.OAuth2SecurityScheme result = new io.a2a.grpc.OAuth2SecurityScheme(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.OAuth2SecurityScheme result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.description_ = description_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.flows_ = flowsBuilder_ == null
            ? flows_
            : flowsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.OAuth2SecurityScheme) {
        return mergeFrom((io.a2a.grpc.OAuth2SecurityScheme)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.OAuth2SecurityScheme other) {
      if (other == io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance()) return this;
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasFlows()) {
        mergeFlows(other.getFlows());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetFlowsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object description_ = "";
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Description of this security scheme.
     * </pre>
     *
     * <code>string description = 1 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private io.a2a.grpc.OAuthFlows flows_;
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OAuthFlows, io.a2a.grpc.OAuthFlows.Builder, io.a2a.grpc.OAuthFlowsOrBuilder> flowsBuilder_;
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     * @return Whether the flows field is set.
     */
    public boolean hasFlows() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     * @return The flows.
     */
    public io.a2a.grpc.OAuthFlows getFlows() {
      if (flowsBuilder_ == null) {
        return flows_ == null ? io.a2a.grpc.OAuthFlows.getDefaultInstance() : flows_;
      } else {
        return flowsBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public Builder setFlows(io.a2a.grpc.OAuthFlows value) {
      if (flowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        flows_ = value;
      } else {
        flowsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public Builder setFlows(
        io.a2a.grpc.OAuthFlows.Builder builderForValue) {
      if (flowsBuilder_ == null) {
        flows_ = builderForValue.build();
      } else {
        flowsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public Builder mergeFlows(io.a2a.grpc.OAuthFlows value) {
      if (flowsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          flows_ != null &&
          flows_ != io.a2a.grpc.OAuthFlows.getDefaultInstance()) {
          getFlowsBuilder().mergeFrom(value);
        } else {
          flows_ = value;
        }
      } else {
        flowsBuilder_.mergeFrom(value);
      }
      if (flows_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public Builder clearFlows() {
      bitField0_ = (bitField0_ & ~0x00000002);
      flows_ = null;
      if (flowsBuilder_ != null) {
        flowsBuilder_.dispose();
        flowsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public io.a2a.grpc.OAuthFlows.Builder getFlowsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetFlowsFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    public io.a2a.grpc.OAuthFlowsOrBuilder getFlowsOrBuilder() {
      if (flowsBuilder_ != null) {
        return flowsBuilder_.getMessageOrBuilder();
      } else {
        return flows_ == null ?
            io.a2a.grpc.OAuthFlows.getDefaultInstance() : flows_;
      }
    }
    /**
     * <pre>
     * An object containing configuration information for the flow types supported
     * </pre>
     *
     * <code>.a2a.v1.OAuthFlows flows = 2 [json_name = "flows"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OAuthFlows, io.a2a.grpc.OAuthFlows.Builder, io.a2a.grpc.OAuthFlowsOrBuilder> 
        internalGetFlowsFieldBuilder() {
      if (flowsBuilder_ == null) {
        flowsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.OAuthFlows, io.a2a.grpc.OAuthFlows.Builder, io.a2a.grpc.OAuthFlowsOrBuilder>(
                getFlows(),
                getParentForChildren(),
                isClean());
        flows_ = null;
      }
      return flowsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.OAuth2SecurityScheme)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.OAuth2SecurityScheme)
  private static final io.a2a.grpc.OAuth2SecurityScheme DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.OAuth2SecurityScheme();
  }

  public static io.a2a.grpc.OAuth2SecurityScheme getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OAuth2SecurityScheme>
      PARSER = new com.google.protobuf.AbstractParser<OAuth2SecurityScheme>() {
    @java.lang.Override
    public OAuth2SecurityScheme parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OAuth2SecurityScheme> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OAuth2SecurityScheme> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.OAuth2SecurityScheme getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

