// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SecuritySchemeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SecurityScheme)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return Whether the apiKeySecurityScheme field is set.
   */
  boolean hasApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return The apiKeySecurityScheme.
   */
  io.a2a.grpc.APIKeySecurityScheme getApiKeySecurityScheme();
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   */
  io.a2a.grpc.APIKeySecuritySchemeOrBuilder getApiKeySecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return Whether the httpAuthSecurityScheme field is set.
   */
  boolean hasHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return The httpAuthSecurityScheme.
   */
  io.a2a.grpc.HTTPAuthSecurityScheme getHttpAuthSecurityScheme();
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   */
  io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder getHttpAuthSecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return Whether the oauth2SecurityScheme field is set.
   */
  boolean hasOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return The oauth2SecurityScheme.
   */
  io.a2a.grpc.OAuth2SecurityScheme getOauth2SecurityScheme();
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   */
  io.a2a.grpc.OAuth2SecuritySchemeOrBuilder getOauth2SecuritySchemeOrBuilder();

  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return Whether the openIdConnectSecurityScheme field is set.
   */
  boolean hasOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return The openIdConnectSecurityScheme.
   */
  io.a2a.grpc.OpenIdConnectSecurityScheme getOpenIdConnectSecurityScheme();
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   */
  io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder getOpenIdConnectSecuritySchemeOrBuilder();

  io.a2a.grpc.SecurityScheme.SchemeCase getSchemeCase();
}
