// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Message request = 1 [json_name = "request", (.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <code>.a2a.v1.Message request = 1 [json_name = "request", (.google.api.field_behavior) = REQUIRED];</code>
   * @return The request.
   */
  io.a2a.grpc.Message getRequest();
  /**
   * <code>.a2a.v1.Message request = 1 [json_name = "request", (.google.api.field_behavior) = REQUIRED];</code>
   */
  io.a2a.grpc.MessageOrBuilder getRequestOrBuilder();

  /**
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   * @return Whether the configuration field is set.
   */
  boolean hasConfiguration();
  /**
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   * @return The configuration.
   */
  io.a2a.grpc.SendMessageConfiguration getConfiguration();
  /**
   * <code>.a2a.v1.SendMessageConfiguration configuration = 2 [json_name = "configuration"];</code>
   */
  io.a2a.grpc.SendMessageConfigurationOrBuilder getConfigurationOrBuilder();

  /**
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  com.google.protobuf.Struct getMetadata();
  /**
   * <code>.google.protobuf.Struct metadata = 3 [json_name = "metadata"];</code>
   */
  com.google.protobuf.StructOrBuilder getMetadataOrBuilder();
}
