// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public final class A2A {
  private A2A() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      A2A.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageConfiguration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Part_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Part_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_FilePart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_FilePart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_DataPart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_DataPart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Artifact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PushNotificationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PushNotificationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthenticationInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentInterface_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentInterface_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCard_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCard_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentProvider_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentProvider_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentCapabilities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentExtension_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentExtension_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AgentSkill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AgentSkill_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskPushNotificationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_StringList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_StringList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Security_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Security_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_Security_SchemesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_Security_SchemesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_APIKeySecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_APIKeySecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OAuth2SecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_OAuthFlows_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_OAuthFlows_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ImplicitOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PasswordOAuthFlow_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PasswordOAuthFlow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_CancelTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_CancelTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_TaskSubscriptionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_TaskSubscriptionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_GetAgentCardRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_GetAgentCardRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_SendMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ta2a.proto\022\006a2a.v1\032\034google/api/annotati" +
      "ons.proto\032\027google/api/client.proto\032\037goog" +
      "le/api/field_behavior.proto\032\033google/prot" +
      "obuf/empty.proto\032\034google/protobuf/struct" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "\236\001\n\030SendMessageConfiguration\022\035\n\025accepted" +
      "_output_modes\030\001 \003(\t\0229\n\021push_notification" +
      "\030\002 \001(\0132\036.a2a.v1.PushNotificationConfig\022\026" +
      "\n\016history_length\030\003 \001(\005\022\020\n\010blocking\030\004 \001(\010" +
      "\"\274\001\n\004Task\022\n\n\002id\030\001 \001(\t\022\022\n\ncontext_id\030\002 \001(" +
      "\t\022\"\n\006status\030\003 \001(\0132\022.a2a.v1.TaskStatus\022#\n" +
      "\tartifacts\030\004 \003(\0132\020.a2a.v1.Artifact\022 \n\007hi" +
      "story\030\005 \003(\0132\017.a2a.v1.Message\022)\n\010metadata" +
      "\030\006 \001(\0132\027.google.protobuf.Struct\"\207\001\n\nTask" +
      "Status\022 \n\005state\030\001 \001(\0162\021.a2a.v1.TaskState" +
      "\022(\n\006update\030\002 \001(\0132\017.a2a.v1.MessageR\007messa" +
      "ge\022-\n\ttimestamp\030\003 \001(\0132\032.google.protobuf." +
      "Timestamp\"b\n\004Part\022\016\n\004text\030\001 \001(\tH\000\022 \n\004fil" +
      "e\030\002 \001(\0132\020.a2a.v1.FilePartH\000\022 \n\004data\030\003 \001(" +
      "\0132\020.a2a.v1.DataPartH\000B\006\n\004part\"Y\n\010FilePar" +
      "t\022\027\n\rfile_with_uri\030\001 \001(\tH\000\022\031\n\017file_with_" +
      "bytes\030\002 \001(\014H\000\022\021\n\tmime_type\030\003 \001(\tB\006\n\004file" +
      "\"1\n\010DataPart\022%\n\004data\030\001 \001(\0132\027.google.prot" +
      "obuf.Struct\"\274\001\n\007Message\022\022\n\nmessage_id\030\001 " +
      "\001(\t\022\022\n\ncontext_id\030\002 \001(\t\022\017\n\007task_id\030\003 \001(\t" +
      "\022\032\n\004role\030\004 \001(\0162\014.a2a.v1.Role\022\035\n\007content\030" +
      "\005 \003(\0132\014.a2a.v1.Part\022)\n\010metadata\030\006 \001(\0132\027." +
      "google.protobuf.Struct\022\022\n\nextensions\030\007 \003" +
      "(\t\"\236\001\n\010Artifact\022\023\n\013artifact_id\030\001 \001(\t\022\014\n\004" +
      "name\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\033\n\005parts" +
      "\030\005 \003(\0132\014.a2a.v1.Part\022)\n\010metadata\030\006 \001(\0132\027" +
      ".google.protobuf.Struct\022\022\n\nextensions\030\007 " +
      "\003(\t\"\232\001\n\025TaskStatusUpdateEvent\022\017\n\007task_id" +
      "\030\001 \001(\t\022\022\n\ncontext_id\030\002 \001(\t\022\"\n\006status\030\003 \001" +
      "(\0132\022.a2a.v1.TaskStatus\022\r\n\005final\030\004 \001(\010\022)\n" +
      "\010metadata\030\005 \001(\0132\027.google.protobuf.Struct" +
      "\"\261\001\n\027TaskArtifactUpdateEvent\022\017\n\007task_id\030" +
      "\001 \001(\t\022\022\n\ncontext_id\030\002 \001(\t\022\"\n\010artifact\030\003 " +
      "\001(\0132\020.a2a.v1.Artifact\022\016\n\006append\030\004 \001(\010\022\022\n" +
      "\nlast_chunk\030\005 \001(\010\022)\n\010metadata\030\006 \001(\0132\027.go" +
      "ogle.protobuf.Struct\"t\n\026PushNotification" +
      "Config\022\n\n\002id\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\r\n\005token" +
      "\030\003 \001(\t\0222\n\016authentication\030\004 \001(\0132\032.a2a.v1." +
      "AuthenticationInfo\":\n\022AuthenticationInfo" +
      "\022\017\n\007schemes\030\001 \003(\t\022\023\n\013credentials\030\002 \001(\t\"0" +
      "\n\016AgentInterface\022\013\n\003url\030\001 \001(\t\022\021\n\ttranspo" +
      "rt\030\002 \001(\t\"\362\004\n\tAgentCard\022\030\n\020protocol_versi" +
      "on\030\020 \001(\t\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 " +
      "\001(\t\022\013\n\003url\030\003 \001(\t\022\033\n\023preferred_transport\030" +
      "\016 \001(\t\0225\n\025additional_interfaces\030\017 \003(\0132\026.a" +
      "2a.v1.AgentInterface\022\'\n\010provider\030\004 \001(\0132\025" +
      ".a2a.v1.AgentProvider\022\017\n\007version\030\005 \001(\t\022\031" +
      "\n\021documentation_url\030\006 \001(\t\022/\n\014capabilitie" +
      "s\030\007 \001(\0132\031.a2a.v1.AgentCapabilities\022@\n\020se" +
      "curity_schemes\030\010 \003(\0132&.a2a.v1.AgentCard." +
      "SecuritySchemesEntry\022\"\n\010security\030\t \003(\0132\020" +
      ".a2a.v1.Security\022\033\n\023default_input_modes\030" +
      "\n \003(\t\022\034\n\024default_output_modes\030\013 \003(\t\022\"\n\006s" +
      "kills\030\014 \003(\0132\022.a2a.v1.AgentSkill\022,\n$suppo" +
      "rts_authenticated_extended_card\030\r \001(\010\032N\n" +
      "\024SecuritySchemesEntry\022\013\n\003key\030\001 \001(\t\022%\n\005va" +
      "lue\030\002 \001(\0132\026.a2a.v1.SecurityScheme:\0028\001\"2\n" +
      "\rAgentProvider\022\013\n\003url\030\001 \001(\t\022\024\n\014organizat" +
      "ion\030\002 \001(\t\"n\n\021AgentCapabilities\022\021\n\tstream" +
      "ing\030\001 \001(\010\022\032\n\022push_notifications\030\002 \001(\010\022*\n" +
      "\nextensions\030\003 \003(\0132\026.a2a.v1.AgentExtensio" +
      "n\"m\n\016AgentExtension\022\013\n\003uri\030\001 \001(\t\022\023\n\013desc" +
      "ription\030\002 \001(\t\022\020\n\010required\030\003 \001(\010\022\'\n\006param" +
      "s\030\004 \001(\0132\027.google.protobuf.Struct\"\206\001\n\nAge" +
      "ntSkill\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013des" +
      "cription\030\003 \001(\t\022\014\n\004tags\030\004 \003(\t\022\020\n\010examples" +
      "\030\005 \003(\t\022\023\n\013input_modes\030\006 \003(\t\022\024\n\014output_mo" +
      "des\030\007 \003(\t\"l\n\032TaskPushNotificationConfig\022" +
      "\014\n\004name\030\001 \001(\t\022@\n\030push_notification_confi" +
      "g\030\002 \001(\0132\036.a2a.v1.PushNotificationConfig\"" +
      "\032\n\nStringList\022\014\n\004list\030\001 \003(\t\"~\n\010Security\022" +
      ".\n\007schemes\030\001 \003(\0132\035.a2a.v1.Security.Schem" +
      "esEntry\032B\n\014SchemesEntry\022\013\n\003key\030\001 \001(\t\022!\n\005" +
      "value\030\002 \001(\0132\022.a2a.v1.StringList:\0028\001\"\260\002\n\016" +
      "SecurityScheme\022?\n\027api_key_security_schem" +
      "e\030\001 \001(\0132\034.a2a.v1.APIKeySecuritySchemeH\000\022" +
      "C\n\031http_auth_security_scheme\030\002 \001(\0132\036.a2a" +
      ".v1.HTTPAuthSecuritySchemeH\000\022>\n\026oauth2_s" +
      "ecurity_scheme\030\003 \001(\0132\034.a2a.v1.OAuth2Secu" +
      "ritySchemeH\000\022N\n\037open_id_connect_security" +
      "_scheme\030\004 \001(\0132#.a2a.v1.OpenIdConnectSecu" +
      "ritySchemeH\000B\010\n\006scheme\"K\n\024APIKeySecurity" +
      "Scheme\022\023\n\013description\030\001 \001(\t\022\020\n\010location\030" +
      "\002 \001(\t\022\014\n\004name\030\003 \001(\t\"T\n\026HTTPAuthSecurityS" +
      "cheme\022\023\n\013description\030\001 \001(\t\022\016\n\006scheme\030\002 \001" +
      "(\t\022\025\n\rbearer_format\030\003 \001(\t\"N\n\024OAuth2Secur" +
      "ityScheme\022\023\n\013description\030\001 \001(\t\022!\n\005flows\030" +
      "\002 \001(\0132\022.a2a.v1.OAuthFlows\"O\n\033OpenIdConne" +
      "ctSecurityScheme\022\023\n\013description\030\001 \001(\t\022\033\n" +
      "\023open_id_connect_url\030\002 \001(\t\"\366\001\n\nOAuthFlow" +
      "s\022@\n\022authorization_code\030\001 \001(\0132\".a2a.v1.A" +
      "uthorizationCodeOAuthFlowH\000\022@\n\022client_cr" +
      "edentials\030\002 \001(\0132\".a2a.v1.ClientCredentia" +
      "lsOAuthFlowH\000\022-\n\010implicit\030\003 \001(\0132\031.a2a.v1" +
      ".ImplicitOAuthFlowH\000\022-\n\010password\030\004 \001(\0132\031" +
      ".a2a.v1.PasswordOAuthFlowH\000B\006\n\004flow\"\316\001\n\032" +
      "AuthorizationCodeOAuthFlow\022\031\n\021authorizat" +
      "ion_url\030\001 \001(\t\022\021\n\ttoken_url\030\002 \001(\t\022\023\n\013refr" +
      "esh_url\030\003 \001(\t\022>\n\006scopes\030\004 \003(\0132..a2a.v1.A" +
      "uthorizationCodeOAuthFlow.ScopesEntry\032-\n" +
      "\013ScopesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"\263\001\n\032ClientCredentialsOAuthFlow\022\021\n\tt" +
      "oken_url\030\001 \001(\t\022\023\n\013refresh_url\030\002 \001(\t\022>\n\006s" +
      "copes\030\003 \003(\0132..a2a.v1.ClientCredentialsOA" +
      "uthFlow.ScopesEntry\032-\n\013ScopesEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\251\001\n\021ImplicitO" +
      "AuthFlow\022\031\n\021authorization_url\030\001 \001(\t\022\023\n\013r" +
      "efresh_url\030\002 \001(\t\0225\n\006scopes\030\003 \003(\0132%.a2a.v" +
      "1.ImplicitOAuthFlow.ScopesEntry\032-\n\013Scope" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\241" +
      "\001\n\021PasswordOAuthFlow\022\021\n\ttoken_url\030\001 \001(\t\022" +
      "\023\n\013refresh_url\030\002 \001(\t\0225\n\006scopes\030\003 \003(\0132%.a" +
      "2a.v1.PasswordOAuthFlow.ScopesEntry\032-\n\013S" +
      "copesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\"\237\001\n\022SendMessageRequest\022%\n\007request\030\001 \001" +
      "(\0132\017.a2a.v1.MessageB\003\340A\002\0227\n\rconfiguratio" +
      "n\030\002 \001(\0132 .a2a.v1.SendMessageConfiguratio" +
      "n\022)\n\010metadata\030\003 \001(\0132\027.google.protobuf.St" +
      "ruct\";\n\016GetTaskRequest\022\021\n\004name\030\001 \001(\tB\003\340A" +
      "\002\022\026\n\016history_length\030\002 \001(\005\"!\n\021CancelTaskR" +
      "equest\022\014\n\004name\030\001 \001(\t\"4\n$GetTaskPushNotif" +
      "icationConfigRequest\022\014\n\004name\030\001 \001(\t\"7\n\'De" +
      "leteTaskPushNotificationConfigRequest\022\014\n" +
      "\004name\030\001 \001(\t\"\217\001\n\'CreateTaskPushNotificati" +
      "onConfigRequest\022\023\n\006parent\030\001 \001(\tB\003\340A\002\022\026\n\t" +
      "config_id\030\002 \001(\tB\003\340A\002\0227\n\006config\030\003 \001(\0132\".a" +
      "2a.v1.TaskPushNotificationConfigB\003\340A\002\"\'\n" +
      "\027TaskSubscriptionRequest\022\014\n\004name\030\001 \001(\t\"^" +
      "\n%ListTaskPushNotificationConfigRequest\022" +
      "\016\n\006parent\030\001 \001(\t\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npa" +
      "ge_token\030\003 \001(\t\"\025\n\023GetAgentCardRequest\"g\n" +
      "\023SendMessageResponse\022\034\n\004task\030\001 \001(\0132\014.a2a" +
      ".v1.TaskH\000\022\'\n\003msg\030\002 \001(\0132\017.a2a.v1.Message" +
      "H\000R\007messageB\t\n\007payload\"\326\001\n\016StreamRespons" +
      "e\022\034\n\004task\030\001 \001(\0132\014.a2a.v1.TaskH\000\022\'\n\003msg\030\002" +
      " \001(\0132\017.a2a.v1.MessageH\000R\007message\0226\n\rstat" +
      "us_update\030\003 \001(\0132\035.a2a.v1.TaskStatusUpdat" +
      "eEventH\000\022:\n\017artifact_update\030\004 \001(\0132\037.a2a." +
      "v1.TaskArtifactUpdateEventH\000B\t\n\007payload\"" +
      "v\n&ListTaskPushNotificationConfigRespons" +
      "e\0223\n\007configs\030\001 \003(\0132\".a2a.v1.TaskPushNoti" +
      "ficationConfig\022\027\n\017next_page_token\030\002 \001(\t*" +
      "\372\001\n\tTaskState\022\032\n\026TASK_STATE_UNSPECIFIED\020" +
      "\000\022\030\n\024TASK_STATE_SUBMITTED\020\001\022\026\n\022TASK_STAT" +
      "E_WORKING\020\002\022\030\n\024TASK_STATE_COMPLETED\020\003\022\025\n" +
      "\021TASK_STATE_FAILED\020\004\022\030\n\024TASK_STATE_CANCE" +
      "LLED\020\005\022\035\n\031TASK_STATE_INPUT_REQUIRED\020\006\022\027\n" +
      "\023TASK_STATE_REJECTED\020\007\022\034\n\030TASK_STATE_AUT" +
      "H_REQUIRED\020\010*;\n\004Role\022\024\n\020ROLE_UNSPECIFIED" +
      "\020\000\022\r\n\tROLE_USER\020\001\022\016\n\nROLE_AGENT\020\0022\272\n\n\nA2" +
      "AService\022c\n\013SendMessage\022\032.a2a.v1.SendMes" +
      "sageRequest\032\033.a2a.v1.SendMessageResponse" +
      "\"\033\202\323\344\223\002\025\"\020/v1/message:send:\001*\022k\n\024SendStr" +
      "eamingMessage\022\032.a2a.v1.SendMessageReques" +
      "t\032\026.a2a.v1.StreamResponse\"\035\202\323\344\223\002\027\"\022/v1/m" +
      "essage:stream:\001*0\001\022R\n\007GetTask\022\026.a2a.v1.G" +
      "etTaskRequest\032\014.a2a.v1.Task\"!\332A\004name\202\323\344\223" +
      "\002\024\022\022/v1/{name=tasks/*}\022[\n\nCancelTask\022\031.a" +
      "2a.v1.CancelTaskRequest\032\014.a2a.v1.Task\"$\202" +
      "\323\344\223\002\036\"\031/v1/{name=tasks/*}:cancel:\001*\022s\n\020T" +
      "askSubscription\022\037.a2a.v1.TaskSubscriptio" +
      "nRequest\032\026.a2a.v1.StreamResponse\"$\202\323\344\223\002\036" +
      "\022\034/v1/{name=tasks/*}:subscribe0\001\022\304\001\n Cre" +
      "ateTaskPushNotificationConfig\022/.a2a.v1.C" +
      "reateTaskPushNotificationConfigRequest\032\"" +
      ".a2a.v1.TaskPushNotificationConfig\"K\332A\rp" +
      "arent,config\202\323\344\223\0025\"+/v1/{parent=task/*/p" +
      "ushNotificationConfigs}:\006config\022\256\001\n\035GetT" +
      "askPushNotificationConfig\022,.a2a.v1.GetTa" +
      "skPushNotificationConfigRequest\032\".a2a.v1" +
      ".TaskPushNotificationConfig\";\332A\004name\202\323\344\223" +
      "\002.\022,/v1/{name=tasks/*/pushNotificationCo" +
      "nfigs/*}\022\276\001\n\036ListTaskPushNotificationCon" +
      "fig\022-.a2a.v1.ListTaskPushNotificationCon" +
      "figRequest\032..a2a.v1.ListTaskPushNotifica" +
      "tionConfigResponse\"=\332A\006parent\202\323\344\223\002.\022,/v1" +
      "/{parent=tasks/*}/pushNotificationConfig" +
      "s\022P\n\014GetAgentCard\022\033.a2a.v1.GetAgentCardR" +
      "equest\032\021.a2a.v1.AgentCard\"\020\202\323\344\223\002\n\022\010/v1/c" +
      "ard\022\250\001\n DeleteTaskPushNotificationConfig" +
      "\022/.a2a.v1.DeleteTaskPushNotificationConf" +
      "igRequest\032\026.google.protobuf.Empty\";\332A\004na" +
      "me\202\323\344\223\002.*,/v1/{name=tasks/*/pushNotifica" +
      "tionConfigs/*}B7\n\013io.a2a.grpcB\003A2AP\001Z\030go" +
      "ogle.golang.org/a2a/v1\252\002\006A2a.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_a2a_v1_SendMessageConfiguration_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_a2a_v1_SendMessageConfiguration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageConfiguration_descriptor,
        new java.lang.String[] { "AcceptedOutputModes", "PushNotification", "HistoryLength", "Blocking", });
    internal_static_a2a_v1_Task_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_a2a_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Task_descriptor,
        new java.lang.String[] { "Id", "ContextId", "Status", "Artifacts", "History", "Metadata", });
    internal_static_a2a_v1_TaskStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_a2a_v1_TaskStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskStatus_descriptor,
        new java.lang.String[] { "State", "Update", "Timestamp", });
    internal_static_a2a_v1_Part_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_a2a_v1_Part_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Part_descriptor,
        new java.lang.String[] { "Text", "File", "Data", "Part", });
    internal_static_a2a_v1_FilePart_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_a2a_v1_FilePart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_FilePart_descriptor,
        new java.lang.String[] { "FileWithUri", "FileWithBytes", "MimeType", "File", });
    internal_static_a2a_v1_DataPart_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_a2a_v1_DataPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_DataPart_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_a2a_v1_Message_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_a2a_v1_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Message_descriptor,
        new java.lang.String[] { "MessageId", "ContextId", "TaskId", "Role", "Content", "Metadata", "Extensions", });
    internal_static_a2a_v1_Artifact_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_a2a_v1_Artifact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Artifact_descriptor,
        new java.lang.String[] { "ArtifactId", "Name", "Description", "Parts", "Metadata", "Extensions", });
    internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_a2a_v1_TaskStatusUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskStatusUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Status", "Final", "Metadata", });
    internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_a2a_v1_TaskArtifactUpdateEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskArtifactUpdateEvent_descriptor,
        new java.lang.String[] { "TaskId", "ContextId", "Artifact", "Append", "LastChunk", "Metadata", });
    internal_static_a2a_v1_PushNotificationConfig_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_a2a_v1_PushNotificationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PushNotificationConfig_descriptor,
        new java.lang.String[] { "Id", "Url", "Token", "Authentication", });
    internal_static_a2a_v1_AuthenticationInfo_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_a2a_v1_AuthenticationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthenticationInfo_descriptor,
        new java.lang.String[] { "Schemes", "Credentials", });
    internal_static_a2a_v1_AgentInterface_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_a2a_v1_AgentInterface_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentInterface_descriptor,
        new java.lang.String[] { "Url", "Transport", });
    internal_static_a2a_v1_AgentCard_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_a2a_v1_AgentCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCard_descriptor,
        new java.lang.String[] { "ProtocolVersion", "Name", "Description", "Url", "PreferredTransport", "AdditionalInterfaces", "Provider", "Version", "DocumentationUrl", "Capabilities", "SecuritySchemes", "Security", "DefaultInputModes", "DefaultOutputModes", "Skills", "SupportsAuthenticatedExtendedCard", });
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor =
      internal_static_a2a_v1_AgentCard_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCard_SecuritySchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_AgentProvider_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_a2a_v1_AgentProvider_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentProvider_descriptor,
        new java.lang.String[] { "Url", "Organization", });
    internal_static_a2a_v1_AgentCapabilities_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_a2a_v1_AgentCapabilities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentCapabilities_descriptor,
        new java.lang.String[] { "Streaming", "PushNotifications", "Extensions", });
    internal_static_a2a_v1_AgentExtension_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_a2a_v1_AgentExtension_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentExtension_descriptor,
        new java.lang.String[] { "Uri", "Description", "Required", "Params", });
    internal_static_a2a_v1_AgentSkill_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_a2a_v1_AgentSkill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AgentSkill_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Tags", "Examples", "InputModes", "OutputModes", });
    internal_static_a2a_v1_TaskPushNotificationConfig_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_a2a_v1_TaskPushNotificationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskPushNotificationConfig_descriptor,
        new java.lang.String[] { "Name", "PushNotificationConfig", });
    internal_static_a2a_v1_StringList_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_a2a_v1_StringList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_StringList_descriptor,
        new java.lang.String[] { "List", });
    internal_static_a2a_v1_Security_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_a2a_v1_Security_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Security_descriptor,
        new java.lang.String[] { "Schemes", });
    internal_static_a2a_v1_Security_SchemesEntry_descriptor =
      internal_static_a2a_v1_Security_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_Security_SchemesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_Security_SchemesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_SecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_a2a_v1_SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SecurityScheme_descriptor,
        new java.lang.String[] { "ApiKeySecurityScheme", "HttpAuthSecurityScheme", "Oauth2SecurityScheme", "OpenIdConnectSecurityScheme", "Scheme", });
    internal_static_a2a_v1_APIKeySecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_a2a_v1_APIKeySecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_APIKeySecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Location", "Name", });
    internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_a2a_v1_HTTPAuthSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_HTTPAuthSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Scheme", "BearerFormat", });
    internal_static_a2a_v1_OAuth2SecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_a2a_v1_OAuth2SecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OAuth2SecurityScheme_descriptor,
        new java.lang.String[] { "Description", "Flows", });
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_a2a_v1_OpenIdConnectSecurityScheme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OpenIdConnectSecurityScheme_descriptor,
        new java.lang.String[] { "Description", "OpenIdConnectUrl", });
    internal_static_a2a_v1_OAuthFlows_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_a2a_v1_OAuthFlows_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_OAuthFlows_descriptor,
        new java.lang.String[] { "AuthorizationCode", "ClientCredentials", "Implicit", "Password", "Flow", });
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_AuthorizationCodeOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_AuthorizationCodeOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(28);
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_ClientCredentialsOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ClientCredentialsOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_ImplicitOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(29);
    internal_static_a2a_v1_ImplicitOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ImplicitOAuthFlow_descriptor,
        new java.lang.String[] { "AuthorizationUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_ImplicitOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ImplicitOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_PasswordOAuthFlow_descriptor =
      getDescriptor().getMessageTypes().get(30);
    internal_static_a2a_v1_PasswordOAuthFlow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PasswordOAuthFlow_descriptor,
        new java.lang.String[] { "TokenUrl", "RefreshUrl", "Scopes", });
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor =
      internal_static_a2a_v1_PasswordOAuthFlow_descriptor.getNestedTypes().get(0);
    internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_PasswordOAuthFlow_ScopesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_a2a_v1_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(31);
    internal_static_a2a_v1_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageRequest_descriptor,
        new java.lang.String[] { "Request", "Configuration", "Metadata", });
    internal_static_a2a_v1_GetTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(32);
    internal_static_a2a_v1_GetTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetTaskRequest_descriptor,
        new java.lang.String[] { "Name", "HistoryLength", });
    internal_static_a2a_v1_CancelTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(33);
    internal_static_a2a_v1_CancelTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_CancelTaskRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(34);
    internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(35);
    internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_DeleteTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(36);
    internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_CreateTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Parent", "ConfigId", "Config", });
    internal_static_a2a_v1_TaskSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(37);
    internal_static_a2a_v1_TaskSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_TaskSubscriptionRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor =
      getDescriptor().getMessageTypes().get(38);
    internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ListTaskPushNotificationConfigRequest_descriptor,
        new java.lang.String[] { "Parent", "PageSize", "PageToken", });
    internal_static_a2a_v1_GetAgentCardRequest_descriptor =
      getDescriptor().getMessageTypes().get(39);
    internal_static_a2a_v1_GetAgentCardRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_GetAgentCardRequest_descriptor,
        new java.lang.String[] { });
    internal_static_a2a_v1_SendMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(40);
    internal_static_a2a_v1_SendMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_SendMessageResponse_descriptor,
        new java.lang.String[] { "Task", "Msg", "Payload", });
    internal_static_a2a_v1_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(41);
    internal_static_a2a_v1_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_StreamResponse_descriptor,
        new java.lang.String[] { "Task", "Msg", "StatusUpdate", "ArtifactUpdate", "Payload", });
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(42);
    internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_a2a_v1_ListTaskPushNotificationConfigResponse_descriptor,
        new java.lang.String[] { "Configs", "NextPageToken", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
