// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * <pre>
 * FilePart represents the different ways files can be provided. If files are
 * small, directly feeding the bytes is supported via file_with_bytes. If the
 * file is large, the agent should read the content as appropriate directly
 * from the file_with_uri source.
 * </pre>
 *
 * Protobuf type {@code a2a.v1.FilePart}
 */
@com.google.protobuf.Generated
public final class FilePart extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.FilePart)
    FilePartOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      FilePart.class.getName());
  }
  // Use FilePart.newBuilder() to construct.
  private FilePart(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private FilePart() {
    mimeType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_FilePart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_FilePart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.FilePart.class, io.a2a.grpc.FilePart.Builder.class);
  }

  private int fileCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object file_;
  public enum FileCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE_WITH_URI(1),
    FILE_WITH_BYTES(2),
    FILE_NOT_SET(0);
    private final int value;
    private FileCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FileCase valueOf(int value) {
      return forNumber(value);
    }

    public static FileCase forNumber(int value) {
      switch (value) {
        case 1: return FILE_WITH_URI;
        case 2: return FILE_WITH_BYTES;
        case 0: return FILE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public FileCase
  getFileCase() {
    return FileCase.forNumber(
        fileCase_);
  }

  public static final int FILE_WITH_URI_FIELD_NUMBER = 1;
  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return Whether the fileWithUri field is set.
   */
  public boolean hasFileWithUri() {
    return fileCase_ == 1;
  }
  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return The fileWithUri.
   */
  public java.lang.String getFileWithUri() {
    java.lang.Object ref = "";
    if (fileCase_ == 1) {
      ref = file_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (fileCase_ == 1) {
        file_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
   * @return The bytes for fileWithUri.
   */
  public com.google.protobuf.ByteString
      getFileWithUriBytes() {
    java.lang.Object ref = "";
    if (fileCase_ == 1) {
      ref = file_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (fileCase_ == 1) {
        file_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_WITH_BYTES_FIELD_NUMBER = 2;
  /**
   * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
   * @return Whether the fileWithBytes field is set.
   */
  @java.lang.Override
  public boolean hasFileWithBytes() {
    return fileCase_ == 2;
  }
  /**
   * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
   * @return The fileWithBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFileWithBytes() {
    if (fileCase_ == 2) {
      return (com.google.protobuf.ByteString) file_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  public static final int MIME_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mimeType_ = "";
  /**
   * <code>string mime_type = 3 [json_name = "mimeType"];</code>
   * @return The mimeType.
   */
  @java.lang.Override
  public java.lang.String getMimeType() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mimeType_ = s;
      return s;
    }
  }
  /**
   * <code>string mime_type = 3 [json_name = "mimeType"];</code>
   * @return The bytes for mimeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mimeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fileCase_ == 1) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, file_);
    }
    if (fileCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) file_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mimeType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, mimeType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fileCase_ == 1) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, file_);
    }
    if (fileCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) file_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mimeType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, mimeType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.FilePart)) {
      return super.equals(obj);
    }
    io.a2a.grpc.FilePart other = (io.a2a.grpc.FilePart) obj;

    if (!getMimeType()
        .equals(other.getMimeType())) return false;
    if (!getFileCase().equals(other.getFileCase())) return false;
    switch (fileCase_) {
      case 1:
        if (!getFileWithUri()
            .equals(other.getFileWithUri())) return false;
        break;
      case 2:
        if (!getFileWithBytes()
            .equals(other.getFileWithBytes())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMimeType().hashCode();
    switch (fileCase_) {
      case 1:
        hash = (37 * hash) + FILE_WITH_URI_FIELD_NUMBER;
        hash = (53 * hash) + getFileWithUri().hashCode();
        break;
      case 2:
        hash = (37 * hash) + FILE_WITH_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getFileWithBytes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.FilePart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.FilePart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.FilePart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.FilePart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.FilePart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.FilePart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.FilePart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * FilePart represents the different ways files can be provided. If files are
   * small, directly feeding the bytes is supported via file_with_bytes. If the
   * file is large, the agent should read the content as appropriate directly
   * from the file_with_uri source.
   * </pre>
   *
   * Protobuf type {@code a2a.v1.FilePart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.FilePart)
      io.a2a.grpc.FilePartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_FilePart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_FilePart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.FilePart.class, io.a2a.grpc.FilePart.Builder.class);
    }

    // Construct using io.a2a.grpc.FilePart.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      mimeType_ = "";
      fileCase_ = 0;
      file_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_FilePart_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.FilePart getDefaultInstanceForType() {
      return io.a2a.grpc.FilePart.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.FilePart build() {
      io.a2a.grpc.FilePart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.FilePart buildPartial() {
      io.a2a.grpc.FilePart result = new io.a2a.grpc.FilePart(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.FilePart result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mimeType_ = mimeType_;
      }
    }

    private void buildPartialOneofs(io.a2a.grpc.FilePart result) {
      result.fileCase_ = fileCase_;
      result.file_ = this.file_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.FilePart) {
        return mergeFrom((io.a2a.grpc.FilePart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.FilePart other) {
      if (other == io.a2a.grpc.FilePart.getDefaultInstance()) return this;
      if (!other.getMimeType().isEmpty()) {
        mimeType_ = other.mimeType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      switch (other.getFileCase()) {
        case FILE_WITH_URI: {
          fileCase_ = 1;
          file_ = other.file_;
          onChanged();
          break;
        }
        case FILE_WITH_BYTES: {
          setFileWithBytes(other.getFileWithBytes());
          break;
        }
        case FILE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              fileCase_ = 1;
              file_ = s;
              break;
            } // case 10
            case 18: {
              file_ = input.readBytes();
              fileCase_ = 2;
              break;
            } // case 18
            case 26: {
              mimeType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int fileCase_ = 0;
    private java.lang.Object file_;
    public FileCase
        getFileCase() {
      return FileCase.forNumber(
          fileCase_);
    }

    public Builder clearFile() {
      fileCase_ = 0;
      file_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @return Whether the fileWithUri field is set.
     */
    @java.lang.Override
    public boolean hasFileWithUri() {
      return fileCase_ == 1;
    }
    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @return The fileWithUri.
     */
    @java.lang.Override
    public java.lang.String getFileWithUri() {
      java.lang.Object ref = "";
      if (fileCase_ == 1) {
        ref = file_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (fileCase_ == 1) {
          file_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @return The bytes for fileWithUri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileWithUriBytes() {
      java.lang.Object ref = "";
      if (fileCase_ == 1) {
        ref = file_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (fileCase_ == 1) {
          file_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @param value The fileWithUri to set.
     * @return This builder for chaining.
     */
    public Builder setFileWithUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fileCase_ = 1;
      file_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFileWithUri() {
      if (fileCase_ == 1) {
        fileCase_ = 0;
        file_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string file_with_uri = 1 [json_name = "fileWithUri"];</code>
     * @param value The bytes for fileWithUri to set.
     * @return This builder for chaining.
     */
    public Builder setFileWithUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileCase_ = 1;
      file_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
     * @return Whether the fileWithBytes field is set.
     */
    public boolean hasFileWithBytes() {
      return fileCase_ == 2;
    }
    /**
     * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
     * @return The fileWithBytes.
     */
    public com.google.protobuf.ByteString getFileWithBytes() {
      if (fileCase_ == 2) {
        return (com.google.protobuf.ByteString) file_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
     * @param value The fileWithBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFileWithBytes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      fileCase_ = 2;
      file_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes file_with_bytes = 2 [json_name = "fileWithBytes"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFileWithBytes() {
      if (fileCase_ == 2) {
        fileCase_ = 0;
        file_ = null;
        onChanged();
      }
      return this;
    }

    private java.lang.Object mimeType_ = "";
    /**
     * <code>string mime_type = 3 [json_name = "mimeType"];</code>
     * @return The mimeType.
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mime_type = 3 [json_name = "mimeType"];</code>
     * @return The bytes for mimeType.
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mime_type = 3 [json_name = "mimeType"];</code>
     * @param value The mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mimeType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string mime_type = 3 [json_name = "mimeType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMimeType() {
      mimeType_ = getDefaultInstance().getMimeType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string mime_type = 3 [json_name = "mimeType"];</code>
     * @param value The bytes for mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mimeType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.FilePart)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.FilePart)
  private static final io.a2a.grpc.FilePart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.FilePart();
  }

  public static io.a2a.grpc.FilePart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FilePart>
      PARSER = new com.google.protobuf.AbstractParser<FilePart>() {
    @java.lang.Override
    public FilePart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FilePart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FilePart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.FilePart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

