// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface ListTaskPushNotificationConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.ListTaskPushNotificationConfigResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .a2a.v1.TaskPushNotificationConfig configs = 1 [json_name = "configs"];</code>
   */
  java.util.List<io.a2a.grpc.TaskPushNotificationConfig> 
      getConfigsList();
  /**
   * <code>repeated .a2a.v1.TaskPushNotificationConfig configs = 1 [json_name = "configs"];</code>
   */
  io.a2a.grpc.TaskPushNotificationConfig getConfigs(int index);
  /**
   * <code>repeated .a2a.v1.TaskPushNotificationConfig configs = 1 [json_name = "configs"];</code>
   */
  int getConfigsCount();
  /**
   * <code>repeated .a2a.v1.TaskPushNotificationConfig configs = 1 [json_name = "configs"];</code>
   */
  java.util.List<? extends io.a2a.grpc.TaskPushNotificationConfigOrBuilder> 
      getConfigsOrBuilderList();
  /**
   * <code>repeated .a2a.v1.TaskPushNotificationConfig configs = 1 [json_name = "configs"];</code>
   */
  io.a2a.grpc.TaskPushNotificationConfigOrBuilder getConfigsOrBuilder(
      int index);

  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * A token, which can be sent as `page_token` to retrieve the next page.
   * If this field is omitted, there are no subsequent pages.
   * </pre>
   *
   * <code>string next_page_token = 2 [json_name = "nextPageToken"];</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
