// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface OAuthFlowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.OAuthFlows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   * @return Whether the authorizationCode field is set.
   */
  boolean hasAuthorizationCode();
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   * @return The authorizationCode.
   */
  io.a2a.grpc.AuthorizationCodeOAuthFlow getAuthorizationCode();
  /**
   * <code>.a2a.v1.AuthorizationCodeOAuthFlow authorization_code = 1 [json_name = "authorizationCode"];</code>
   */
  io.a2a.grpc.AuthorizationCodeOAuthFlowOrBuilder getAuthorizationCodeOrBuilder();

  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   * @return Whether the clientCredentials field is set.
   */
  boolean hasClientCredentials();
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   * @return The clientCredentials.
   */
  io.a2a.grpc.ClientCredentialsOAuthFlow getClientCredentials();
  /**
   * <code>.a2a.v1.ClientCredentialsOAuthFlow client_credentials = 2 [json_name = "clientCredentials"];</code>
   */
  io.a2a.grpc.ClientCredentialsOAuthFlowOrBuilder getClientCredentialsOrBuilder();

  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   * @return Whether the implicit field is set.
   */
  boolean hasImplicit();
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   * @return The implicit.
   */
  io.a2a.grpc.ImplicitOAuthFlow getImplicit();
  /**
   * <code>.a2a.v1.ImplicitOAuthFlow implicit = 3 [json_name = "implicit"];</code>
   */
  io.a2a.grpc.ImplicitOAuthFlowOrBuilder getImplicitOrBuilder();

  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   * @return Whether the password field is set.
   */
  boolean hasPassword();
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   * @return The password.
   */
  io.a2a.grpc.PasswordOAuthFlow getPassword();
  /**
   * <code>.a2a.v1.PasswordOAuthFlow password = 4 [json_name = "password"];</code>
   */
  io.a2a.grpc.PasswordOAuthFlowOrBuilder getPasswordOrBuilder();

  io.a2a.grpc.OAuthFlows.FlowCase getFlowCase();
}
