// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface PartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.Part)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>.a2a.v1.FilePart file = 2 [json_name = "file"];</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>.a2a.v1.FilePart file = 2 [json_name = "file"];</code>
   * @return The file.
   */
  io.a2a.grpc.FilePart getFile();
  /**
   * <code>.a2a.v1.FilePart file = 2 [json_name = "file"];</code>
   */
  io.a2a.grpc.FilePartOrBuilder getFileOrBuilder();

  /**
   * <code>.a2a.v1.DataPart data = 3 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.a2a.v1.DataPart data = 3 [json_name = "data"];</code>
   * @return The data.
   */
  io.a2a.grpc.DataPart getData();
  /**
   * <code>.a2a.v1.DataPart data = 3 [json_name = "data"];</code>
   */
  io.a2a.grpc.DataPartOrBuilder getDataOrBuilder();

  io.a2a.grpc.Part.PartCase getPartCase();
}
