// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * Protobuf type {@code a2a.v1.SecurityScheme}
 */
@com.google.protobuf.Generated
public final class SecurityScheme extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.SecurityScheme)
    SecuritySchemeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      SecurityScheme.class.getName());
  }
  // Use SecurityScheme.newBuilder() to construct.
  private SecurityScheme(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SecurityScheme() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_SecurityScheme_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_SecurityScheme_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.SecurityScheme.class, io.a2a.grpc.SecurityScheme.Builder.class);
  }

  private int schemeCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object scheme_;
  public enum SchemeCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    API_KEY_SECURITY_SCHEME(1),
    HTTP_AUTH_SECURITY_SCHEME(2),
    OAUTH2_SECURITY_SCHEME(3),
    OPEN_ID_CONNECT_SECURITY_SCHEME(4),
    SCHEME_NOT_SET(0);
    private final int value;
    private SchemeCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SchemeCase valueOf(int value) {
      return forNumber(value);
    }

    public static SchemeCase forNumber(int value) {
      switch (value) {
        case 1: return API_KEY_SECURITY_SCHEME;
        case 2: return HTTP_AUTH_SECURITY_SCHEME;
        case 3: return OAUTH2_SECURITY_SCHEME;
        case 4: return OPEN_ID_CONNECT_SECURITY_SCHEME;
        case 0: return SCHEME_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public SchemeCase
  getSchemeCase() {
    return SchemeCase.forNumber(
        schemeCase_);
  }

  public static final int API_KEY_SECURITY_SCHEME_FIELD_NUMBER = 1;
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return Whether the apiKeySecurityScheme field is set.
   */
  @java.lang.Override
  public boolean hasApiKeySecurityScheme() {
    return schemeCase_ == 1;
  }
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   * @return The apiKeySecurityScheme.
   */
  @java.lang.Override
  public io.a2a.grpc.APIKeySecurityScheme getApiKeySecurityScheme() {
    if (schemeCase_ == 1) {
       return (io.a2a.grpc.APIKeySecurityScheme) scheme_;
    }
    return io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.APIKeySecuritySchemeOrBuilder getApiKeySecuritySchemeOrBuilder() {
    if (schemeCase_ == 1) {
       return (io.a2a.grpc.APIKeySecurityScheme) scheme_;
    }
    return io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
  }

  public static final int HTTP_AUTH_SECURITY_SCHEME_FIELD_NUMBER = 2;
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return Whether the httpAuthSecurityScheme field is set.
   */
  @java.lang.Override
  public boolean hasHttpAuthSecurityScheme() {
    return schemeCase_ == 2;
  }
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   * @return The httpAuthSecurityScheme.
   */
  @java.lang.Override
  public io.a2a.grpc.HTTPAuthSecurityScheme getHttpAuthSecurityScheme() {
    if (schemeCase_ == 2) {
       return (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_;
    }
    return io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder getHttpAuthSecuritySchemeOrBuilder() {
    if (schemeCase_ == 2) {
       return (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_;
    }
    return io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
  }

  public static final int OAUTH2_SECURITY_SCHEME_FIELD_NUMBER = 3;
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return Whether the oauth2SecurityScheme field is set.
   */
  @java.lang.Override
  public boolean hasOauth2SecurityScheme() {
    return schemeCase_ == 3;
  }
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   * @return The oauth2SecurityScheme.
   */
  @java.lang.Override
  public io.a2a.grpc.OAuth2SecurityScheme getOauth2SecurityScheme() {
    if (schemeCase_ == 3) {
       return (io.a2a.grpc.OAuth2SecurityScheme) scheme_;
    }
    return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.OAuth2SecuritySchemeOrBuilder getOauth2SecuritySchemeOrBuilder() {
    if (schemeCase_ == 3) {
       return (io.a2a.grpc.OAuth2SecurityScheme) scheme_;
    }
    return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
  }

  public static final int OPEN_ID_CONNECT_SECURITY_SCHEME_FIELD_NUMBER = 4;
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return Whether the openIdConnectSecurityScheme field is set.
   */
  @java.lang.Override
  public boolean hasOpenIdConnectSecurityScheme() {
    return schemeCase_ == 4;
  }
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   * @return The openIdConnectSecurityScheme.
   */
  @java.lang.Override
  public io.a2a.grpc.OpenIdConnectSecurityScheme getOpenIdConnectSecurityScheme() {
    if (schemeCase_ == 4) {
       return (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_;
    }
    return io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder getOpenIdConnectSecuritySchemeOrBuilder() {
    if (schemeCase_ == 4) {
       return (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_;
    }
    return io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schemeCase_ == 1) {
      output.writeMessage(1, (io.a2a.grpc.APIKeySecurityScheme) scheme_);
    }
    if (schemeCase_ == 2) {
      output.writeMessage(2, (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_);
    }
    if (schemeCase_ == 3) {
      output.writeMessage(3, (io.a2a.grpc.OAuth2SecurityScheme) scheme_);
    }
    if (schemeCase_ == 4) {
      output.writeMessage(4, (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schemeCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.a2a.grpc.APIKeySecurityScheme) scheme_);
    }
    if (schemeCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_);
    }
    if (schemeCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.a2a.grpc.OAuth2SecurityScheme) scheme_);
    }
    if (schemeCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.SecurityScheme)) {
      return super.equals(obj);
    }
    io.a2a.grpc.SecurityScheme other = (io.a2a.grpc.SecurityScheme) obj;

    if (!getSchemeCase().equals(other.getSchemeCase())) return false;
    switch (schemeCase_) {
      case 1:
        if (!getApiKeySecurityScheme()
            .equals(other.getApiKeySecurityScheme())) return false;
        break;
      case 2:
        if (!getHttpAuthSecurityScheme()
            .equals(other.getHttpAuthSecurityScheme())) return false;
        break;
      case 3:
        if (!getOauth2SecurityScheme()
            .equals(other.getOauth2SecurityScheme())) return false;
        break;
      case 4:
        if (!getOpenIdConnectSecurityScheme()
            .equals(other.getOpenIdConnectSecurityScheme())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (schemeCase_) {
      case 1:
        hash = (37 * hash) + API_KEY_SECURITY_SCHEME_FIELD_NUMBER;
        hash = (53 * hash) + getApiKeySecurityScheme().hashCode();
        break;
      case 2:
        hash = (37 * hash) + HTTP_AUTH_SECURITY_SCHEME_FIELD_NUMBER;
        hash = (53 * hash) + getHttpAuthSecurityScheme().hashCode();
        break;
      case 3:
        hash = (37 * hash) + OAUTH2_SECURITY_SCHEME_FIELD_NUMBER;
        hash = (53 * hash) + getOauth2SecurityScheme().hashCode();
        break;
      case 4:
        hash = (37 * hash) + OPEN_ID_CONNECT_SECURITY_SCHEME_FIELD_NUMBER;
        hash = (53 * hash) + getOpenIdConnectSecurityScheme().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.SecurityScheme parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.SecurityScheme parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.SecurityScheme parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.SecurityScheme parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.SecurityScheme prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code a2a.v1.SecurityScheme}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.SecurityScheme)
      io.a2a.grpc.SecuritySchemeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SecurityScheme_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SecurityScheme_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.SecurityScheme.class, io.a2a.grpc.SecurityScheme.Builder.class);
    }

    // Construct using io.a2a.grpc.SecurityScheme.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (apiKeySecuritySchemeBuilder_ != null) {
        apiKeySecuritySchemeBuilder_.clear();
      }
      if (httpAuthSecuritySchemeBuilder_ != null) {
        httpAuthSecuritySchemeBuilder_.clear();
      }
      if (oauth2SecuritySchemeBuilder_ != null) {
        oauth2SecuritySchemeBuilder_.clear();
      }
      if (openIdConnectSecuritySchemeBuilder_ != null) {
        openIdConnectSecuritySchemeBuilder_.clear();
      }
      schemeCase_ = 0;
      scheme_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_SecurityScheme_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.SecurityScheme getDefaultInstanceForType() {
      return io.a2a.grpc.SecurityScheme.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.SecurityScheme build() {
      io.a2a.grpc.SecurityScheme result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.SecurityScheme buildPartial() {
      io.a2a.grpc.SecurityScheme result = new io.a2a.grpc.SecurityScheme(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.SecurityScheme result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.a2a.grpc.SecurityScheme result) {
      result.schemeCase_ = schemeCase_;
      result.scheme_ = this.scheme_;
      if (schemeCase_ == 1 &&
          apiKeySecuritySchemeBuilder_ != null) {
        result.scheme_ = apiKeySecuritySchemeBuilder_.build();
      }
      if (schemeCase_ == 2 &&
          httpAuthSecuritySchemeBuilder_ != null) {
        result.scheme_ = httpAuthSecuritySchemeBuilder_.build();
      }
      if (schemeCase_ == 3 &&
          oauth2SecuritySchemeBuilder_ != null) {
        result.scheme_ = oauth2SecuritySchemeBuilder_.build();
      }
      if (schemeCase_ == 4 &&
          openIdConnectSecuritySchemeBuilder_ != null) {
        result.scheme_ = openIdConnectSecuritySchemeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.SecurityScheme) {
        return mergeFrom((io.a2a.grpc.SecurityScheme)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.SecurityScheme other) {
      if (other == io.a2a.grpc.SecurityScheme.getDefaultInstance()) return this;
      switch (other.getSchemeCase()) {
        case API_KEY_SECURITY_SCHEME: {
          mergeApiKeySecurityScheme(other.getApiKeySecurityScheme());
          break;
        }
        case HTTP_AUTH_SECURITY_SCHEME: {
          mergeHttpAuthSecurityScheme(other.getHttpAuthSecurityScheme());
          break;
        }
        case OAUTH2_SECURITY_SCHEME: {
          mergeOauth2SecurityScheme(other.getOauth2SecurityScheme());
          break;
        }
        case OPEN_ID_CONNECT_SECURITY_SCHEME: {
          mergeOpenIdConnectSecurityScheme(other.getOpenIdConnectSecurityScheme());
          break;
        }
        case SCHEME_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetApiKeySecuritySchemeFieldBuilder().getBuilder(),
                  extensionRegistry);
              schemeCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetHttpAuthSecuritySchemeFieldBuilder().getBuilder(),
                  extensionRegistry);
              schemeCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetOauth2SecuritySchemeFieldBuilder().getBuilder(),
                  extensionRegistry);
              schemeCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetOpenIdConnectSecuritySchemeFieldBuilder().getBuilder(),
                  extensionRegistry);
              schemeCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int schemeCase_ = 0;
    private java.lang.Object scheme_;
    public SchemeCase
        getSchemeCase() {
      return SchemeCase.forNumber(
          schemeCase_);
    }

    public Builder clearScheme() {
      schemeCase_ = 0;
      scheme_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.APIKeySecurityScheme, io.a2a.grpc.APIKeySecurityScheme.Builder, io.a2a.grpc.APIKeySecuritySchemeOrBuilder> apiKeySecuritySchemeBuilder_;
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     * @return Whether the apiKeySecurityScheme field is set.
     */
    @java.lang.Override
    public boolean hasApiKeySecurityScheme() {
      return schemeCase_ == 1;
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     * @return The apiKeySecurityScheme.
     */
    @java.lang.Override
    public io.a2a.grpc.APIKeySecurityScheme getApiKeySecurityScheme() {
      if (apiKeySecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 1) {
          return (io.a2a.grpc.APIKeySecurityScheme) scheme_;
        }
        return io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
      } else {
        if (schemeCase_ == 1) {
          return apiKeySecuritySchemeBuilder_.getMessage();
        }
        return io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    public Builder setApiKeySecurityScheme(io.a2a.grpc.APIKeySecurityScheme value) {
      if (apiKeySecuritySchemeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scheme_ = value;
        onChanged();
      } else {
        apiKeySecuritySchemeBuilder_.setMessage(value);
      }
      schemeCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    public Builder setApiKeySecurityScheme(
        io.a2a.grpc.APIKeySecurityScheme.Builder builderForValue) {
      if (apiKeySecuritySchemeBuilder_ == null) {
        scheme_ = builderForValue.build();
        onChanged();
      } else {
        apiKeySecuritySchemeBuilder_.setMessage(builderForValue.build());
      }
      schemeCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    public Builder mergeApiKeySecurityScheme(io.a2a.grpc.APIKeySecurityScheme value) {
      if (apiKeySecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 1 &&
            scheme_ != io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance()) {
          scheme_ = io.a2a.grpc.APIKeySecurityScheme.newBuilder((io.a2a.grpc.APIKeySecurityScheme) scheme_)
              .mergeFrom(value).buildPartial();
        } else {
          scheme_ = value;
        }
        onChanged();
      } else {
        if (schemeCase_ == 1) {
          apiKeySecuritySchemeBuilder_.mergeFrom(value);
        } else {
          apiKeySecuritySchemeBuilder_.setMessage(value);
        }
      }
      schemeCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    public Builder clearApiKeySecurityScheme() {
      if (apiKeySecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 1) {
          schemeCase_ = 0;
          scheme_ = null;
          onChanged();
        }
      } else {
        if (schemeCase_ == 1) {
          schemeCase_ = 0;
          scheme_ = null;
        }
        apiKeySecuritySchemeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    public io.a2a.grpc.APIKeySecurityScheme.Builder getApiKeySecuritySchemeBuilder() {
      return internalGetApiKeySecuritySchemeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.APIKeySecuritySchemeOrBuilder getApiKeySecuritySchemeOrBuilder() {
      if ((schemeCase_ == 1) && (apiKeySecuritySchemeBuilder_ != null)) {
        return apiKeySecuritySchemeBuilder_.getMessageOrBuilder();
      } else {
        if (schemeCase_ == 1) {
          return (io.a2a.grpc.APIKeySecurityScheme) scheme_;
        }
        return io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.APIKeySecurityScheme api_key_security_scheme = 1 [json_name = "apiKeySecurityScheme"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.APIKeySecurityScheme, io.a2a.grpc.APIKeySecurityScheme.Builder, io.a2a.grpc.APIKeySecuritySchemeOrBuilder> 
        internalGetApiKeySecuritySchemeFieldBuilder() {
      if (apiKeySecuritySchemeBuilder_ == null) {
        if (!(schemeCase_ == 1)) {
          scheme_ = io.a2a.grpc.APIKeySecurityScheme.getDefaultInstance();
        }
        apiKeySecuritySchemeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.APIKeySecurityScheme, io.a2a.grpc.APIKeySecurityScheme.Builder, io.a2a.grpc.APIKeySecuritySchemeOrBuilder>(
                (io.a2a.grpc.APIKeySecurityScheme) scheme_,
                getParentForChildren(),
                isClean());
        scheme_ = null;
      }
      schemeCase_ = 1;
      onChanged();
      return apiKeySecuritySchemeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.HTTPAuthSecurityScheme, io.a2a.grpc.HTTPAuthSecurityScheme.Builder, io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder> httpAuthSecuritySchemeBuilder_;
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     * @return Whether the httpAuthSecurityScheme field is set.
     */
    @java.lang.Override
    public boolean hasHttpAuthSecurityScheme() {
      return schemeCase_ == 2;
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     * @return The httpAuthSecurityScheme.
     */
    @java.lang.Override
    public io.a2a.grpc.HTTPAuthSecurityScheme getHttpAuthSecurityScheme() {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 2) {
          return (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_;
        }
        return io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
      } else {
        if (schemeCase_ == 2) {
          return httpAuthSecuritySchemeBuilder_.getMessage();
        }
        return io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    public Builder setHttpAuthSecurityScheme(io.a2a.grpc.HTTPAuthSecurityScheme value) {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scheme_ = value;
        onChanged();
      } else {
        httpAuthSecuritySchemeBuilder_.setMessage(value);
      }
      schemeCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    public Builder setHttpAuthSecurityScheme(
        io.a2a.grpc.HTTPAuthSecurityScheme.Builder builderForValue) {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        scheme_ = builderForValue.build();
        onChanged();
      } else {
        httpAuthSecuritySchemeBuilder_.setMessage(builderForValue.build());
      }
      schemeCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    public Builder mergeHttpAuthSecurityScheme(io.a2a.grpc.HTTPAuthSecurityScheme value) {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 2 &&
            scheme_ != io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance()) {
          scheme_ = io.a2a.grpc.HTTPAuthSecurityScheme.newBuilder((io.a2a.grpc.HTTPAuthSecurityScheme) scheme_)
              .mergeFrom(value).buildPartial();
        } else {
          scheme_ = value;
        }
        onChanged();
      } else {
        if (schemeCase_ == 2) {
          httpAuthSecuritySchemeBuilder_.mergeFrom(value);
        } else {
          httpAuthSecuritySchemeBuilder_.setMessage(value);
        }
      }
      schemeCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    public Builder clearHttpAuthSecurityScheme() {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 2) {
          schemeCase_ = 0;
          scheme_ = null;
          onChanged();
        }
      } else {
        if (schemeCase_ == 2) {
          schemeCase_ = 0;
          scheme_ = null;
        }
        httpAuthSecuritySchemeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    public io.a2a.grpc.HTTPAuthSecurityScheme.Builder getHttpAuthSecuritySchemeBuilder() {
      return internalGetHttpAuthSecuritySchemeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder getHttpAuthSecuritySchemeOrBuilder() {
      if ((schemeCase_ == 2) && (httpAuthSecuritySchemeBuilder_ != null)) {
        return httpAuthSecuritySchemeBuilder_.getMessageOrBuilder();
      } else {
        if (schemeCase_ == 2) {
          return (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_;
        }
        return io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.HTTPAuthSecurityScheme http_auth_security_scheme = 2 [json_name = "httpAuthSecurityScheme"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.HTTPAuthSecurityScheme, io.a2a.grpc.HTTPAuthSecurityScheme.Builder, io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder> 
        internalGetHttpAuthSecuritySchemeFieldBuilder() {
      if (httpAuthSecuritySchemeBuilder_ == null) {
        if (!(schemeCase_ == 2)) {
          scheme_ = io.a2a.grpc.HTTPAuthSecurityScheme.getDefaultInstance();
        }
        httpAuthSecuritySchemeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.HTTPAuthSecurityScheme, io.a2a.grpc.HTTPAuthSecurityScheme.Builder, io.a2a.grpc.HTTPAuthSecuritySchemeOrBuilder>(
                (io.a2a.grpc.HTTPAuthSecurityScheme) scheme_,
                getParentForChildren(),
                isClean());
        scheme_ = null;
      }
      schemeCase_ = 2;
      onChanged();
      return httpAuthSecuritySchemeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OAuth2SecurityScheme, io.a2a.grpc.OAuth2SecurityScheme.Builder, io.a2a.grpc.OAuth2SecuritySchemeOrBuilder> oauth2SecuritySchemeBuilder_;
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     * @return Whether the oauth2SecurityScheme field is set.
     */
    @java.lang.Override
    public boolean hasOauth2SecurityScheme() {
      return schemeCase_ == 3;
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     * @return The oauth2SecurityScheme.
     */
    @java.lang.Override
    public io.a2a.grpc.OAuth2SecurityScheme getOauth2SecurityScheme() {
      if (oauth2SecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 3) {
          return (io.a2a.grpc.OAuth2SecurityScheme) scheme_;
        }
        return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
      } else {
        if (schemeCase_ == 3) {
          return oauth2SecuritySchemeBuilder_.getMessage();
        }
        return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    public Builder setOauth2SecurityScheme(io.a2a.grpc.OAuth2SecurityScheme value) {
      if (oauth2SecuritySchemeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scheme_ = value;
        onChanged();
      } else {
        oauth2SecuritySchemeBuilder_.setMessage(value);
      }
      schemeCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    public Builder setOauth2SecurityScheme(
        io.a2a.grpc.OAuth2SecurityScheme.Builder builderForValue) {
      if (oauth2SecuritySchemeBuilder_ == null) {
        scheme_ = builderForValue.build();
        onChanged();
      } else {
        oauth2SecuritySchemeBuilder_.setMessage(builderForValue.build());
      }
      schemeCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    public Builder mergeOauth2SecurityScheme(io.a2a.grpc.OAuth2SecurityScheme value) {
      if (oauth2SecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 3 &&
            scheme_ != io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance()) {
          scheme_ = io.a2a.grpc.OAuth2SecurityScheme.newBuilder((io.a2a.grpc.OAuth2SecurityScheme) scheme_)
              .mergeFrom(value).buildPartial();
        } else {
          scheme_ = value;
        }
        onChanged();
      } else {
        if (schemeCase_ == 3) {
          oauth2SecuritySchemeBuilder_.mergeFrom(value);
        } else {
          oauth2SecuritySchemeBuilder_.setMessage(value);
        }
      }
      schemeCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    public Builder clearOauth2SecurityScheme() {
      if (oauth2SecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 3) {
          schemeCase_ = 0;
          scheme_ = null;
          onChanged();
        }
      } else {
        if (schemeCase_ == 3) {
          schemeCase_ = 0;
          scheme_ = null;
        }
        oauth2SecuritySchemeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    public io.a2a.grpc.OAuth2SecurityScheme.Builder getOauth2SecuritySchemeBuilder() {
      return internalGetOauth2SecuritySchemeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.OAuth2SecuritySchemeOrBuilder getOauth2SecuritySchemeOrBuilder() {
      if ((schemeCase_ == 3) && (oauth2SecuritySchemeBuilder_ != null)) {
        return oauth2SecuritySchemeBuilder_.getMessageOrBuilder();
      } else {
        if (schemeCase_ == 3) {
          return (io.a2a.grpc.OAuth2SecurityScheme) scheme_;
        }
        return io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.OAuth2SecurityScheme oauth2_security_scheme = 3 [json_name = "oauth2SecurityScheme"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OAuth2SecurityScheme, io.a2a.grpc.OAuth2SecurityScheme.Builder, io.a2a.grpc.OAuth2SecuritySchemeOrBuilder> 
        internalGetOauth2SecuritySchemeFieldBuilder() {
      if (oauth2SecuritySchemeBuilder_ == null) {
        if (!(schemeCase_ == 3)) {
          scheme_ = io.a2a.grpc.OAuth2SecurityScheme.getDefaultInstance();
        }
        oauth2SecuritySchemeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.OAuth2SecurityScheme, io.a2a.grpc.OAuth2SecurityScheme.Builder, io.a2a.grpc.OAuth2SecuritySchemeOrBuilder>(
                (io.a2a.grpc.OAuth2SecurityScheme) scheme_,
                getParentForChildren(),
                isClean());
        scheme_ = null;
      }
      schemeCase_ = 3;
      onChanged();
      return oauth2SecuritySchemeBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OpenIdConnectSecurityScheme, io.a2a.grpc.OpenIdConnectSecurityScheme.Builder, io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder> openIdConnectSecuritySchemeBuilder_;
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     * @return Whether the openIdConnectSecurityScheme field is set.
     */
    @java.lang.Override
    public boolean hasOpenIdConnectSecurityScheme() {
      return schemeCase_ == 4;
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     * @return The openIdConnectSecurityScheme.
     */
    @java.lang.Override
    public io.a2a.grpc.OpenIdConnectSecurityScheme getOpenIdConnectSecurityScheme() {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 4) {
          return (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_;
        }
        return io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
      } else {
        if (schemeCase_ == 4) {
          return openIdConnectSecuritySchemeBuilder_.getMessage();
        }
        return io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    public Builder setOpenIdConnectSecurityScheme(io.a2a.grpc.OpenIdConnectSecurityScheme value) {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scheme_ = value;
        onChanged();
      } else {
        openIdConnectSecuritySchemeBuilder_.setMessage(value);
      }
      schemeCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    public Builder setOpenIdConnectSecurityScheme(
        io.a2a.grpc.OpenIdConnectSecurityScheme.Builder builderForValue) {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        scheme_ = builderForValue.build();
        onChanged();
      } else {
        openIdConnectSecuritySchemeBuilder_.setMessage(builderForValue.build());
      }
      schemeCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    public Builder mergeOpenIdConnectSecurityScheme(io.a2a.grpc.OpenIdConnectSecurityScheme value) {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 4 &&
            scheme_ != io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance()) {
          scheme_ = io.a2a.grpc.OpenIdConnectSecurityScheme.newBuilder((io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_)
              .mergeFrom(value).buildPartial();
        } else {
          scheme_ = value;
        }
        onChanged();
      } else {
        if (schemeCase_ == 4) {
          openIdConnectSecuritySchemeBuilder_.mergeFrom(value);
        } else {
          openIdConnectSecuritySchemeBuilder_.setMessage(value);
        }
      }
      schemeCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    public Builder clearOpenIdConnectSecurityScheme() {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        if (schemeCase_ == 4) {
          schemeCase_ = 0;
          scheme_ = null;
          onChanged();
        }
      } else {
        if (schemeCase_ == 4) {
          schemeCase_ = 0;
          scheme_ = null;
        }
        openIdConnectSecuritySchemeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    public io.a2a.grpc.OpenIdConnectSecurityScheme.Builder getOpenIdConnectSecuritySchemeBuilder() {
      return internalGetOpenIdConnectSecuritySchemeFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder getOpenIdConnectSecuritySchemeOrBuilder() {
      if ((schemeCase_ == 4) && (openIdConnectSecuritySchemeBuilder_ != null)) {
        return openIdConnectSecuritySchemeBuilder_.getMessageOrBuilder();
      } else {
        if (schemeCase_ == 4) {
          return (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_;
        }
        return io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.OpenIdConnectSecurityScheme open_id_connect_security_scheme = 4 [json_name = "openIdConnectSecurityScheme"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.OpenIdConnectSecurityScheme, io.a2a.grpc.OpenIdConnectSecurityScheme.Builder, io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder> 
        internalGetOpenIdConnectSecuritySchemeFieldBuilder() {
      if (openIdConnectSecuritySchemeBuilder_ == null) {
        if (!(schemeCase_ == 4)) {
          scheme_ = io.a2a.grpc.OpenIdConnectSecurityScheme.getDefaultInstance();
        }
        openIdConnectSecuritySchemeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.OpenIdConnectSecurityScheme, io.a2a.grpc.OpenIdConnectSecurityScheme.Builder, io.a2a.grpc.OpenIdConnectSecuritySchemeOrBuilder>(
                (io.a2a.grpc.OpenIdConnectSecurityScheme) scheme_,
                getParentForChildren(),
                isClean());
        scheme_ = null;
      }
      schemeCase_ = 4;
      onChanged();
      return openIdConnectSecuritySchemeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.SecurityScheme)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.SecurityScheme)
  private static final io.a2a.grpc.SecurityScheme DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.SecurityScheme();
  }

  public static io.a2a.grpc.SecurityScheme getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SecurityScheme>
      PARSER = new com.google.protobuf.AbstractParser<SecurityScheme>() {
    @java.lang.Override
    public SecurityScheme parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SecurityScheme> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SecurityScheme> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.SecurityScheme getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

