// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface SendMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.SendMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  io.a2a.grpc.Task getTask();
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   */
  io.a2a.grpc.TaskOrBuilder getTaskOrBuilder();

  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  io.a2a.grpc.Message getMsg();
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  io.a2a.grpc.MessageOrBuilder getMsgOrBuilder();

  io.a2a.grpc.SendMessageResponse.PayloadCase getPayloadCase();
}
