// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

/**
 * <pre>
 * The stream response for a message. The stream should be one of the following
 * sequences:
 * If the response is a message, the stream should contain one, and only one,
 * message and then close
 * If the response is a task lifecycle, the first response should be a Task
 * object followed by zero or more TaskStatusUpdateEvents and
 * TaskArtifactUpdateEvents. The stream should complete when the Task
 * if in an interrupted or terminal state. A stream that ends before these
 * conditions are met are
 * </pre>
 *
 * Protobuf type {@code a2a.v1.StreamResponse}
 */
@com.google.protobuf.Generated
public final class StreamResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:a2a.v1.StreamResponse)
    StreamResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      StreamResponse.class.getName());
  }
  // Use StreamResponse.newBuilder() to construct.
  private StreamResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StreamResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_StreamResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.a2a.grpc.A2A.internal_static_a2a_v1_StreamResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.a2a.grpc.StreamResponse.class, io.a2a.grpc.StreamResponse.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TASK(1),
    MSG(2),
    STATUS_UPDATE(3),
    ARTIFACT_UPDATE(4),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1: return TASK;
        case 2: return MSG;
        case 3: return STATUS_UPDATE;
        case 4: return ARTIFACT_UPDATE;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TASK_FIELD_NUMBER = 1;
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  @java.lang.Override
  public boolean hasTask() {
    return payloadCase_ == 1;
  }
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  @java.lang.Override
  public io.a2a.grpc.Task getTask() {
    if (payloadCase_ == 1) {
       return (io.a2a.grpc.Task) payload_;
    }
    return io.a2a.grpc.Task.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.TaskOrBuilder getTaskOrBuilder() {
    if (payloadCase_ == 1) {
       return (io.a2a.grpc.Task) payload_;
    }
    return io.a2a.grpc.Task.getDefaultInstance();
  }

  public static final int MSG_FIELD_NUMBER = 2;
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return Whether the msg field is set.
   */
  @java.lang.Override
  public boolean hasMsg() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   * @return The msg.
   */
  @java.lang.Override
  public io.a2a.grpc.Message getMsg() {
    if (payloadCase_ == 2) {
       return (io.a2a.grpc.Message) payload_;
    }
    return io.a2a.grpc.Message.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.MessageOrBuilder getMsgOrBuilder() {
    if (payloadCase_ == 2) {
       return (io.a2a.grpc.Message) payload_;
    }
    return io.a2a.grpc.Message.getDefaultInstance();
  }

  public static final int STATUS_UPDATE_FIELD_NUMBER = 3;
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   * @return Whether the statusUpdate field is set.
   */
  @java.lang.Override
  public boolean hasStatusUpdate() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   * @return The statusUpdate.
   */
  @java.lang.Override
  public io.a2a.grpc.TaskStatusUpdateEvent getStatusUpdate() {
    if (payloadCase_ == 3) {
       return (io.a2a.grpc.TaskStatusUpdateEvent) payload_;
    }
    return io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.TaskStatusUpdateEventOrBuilder getStatusUpdateOrBuilder() {
    if (payloadCase_ == 3) {
       return (io.a2a.grpc.TaskStatusUpdateEvent) payload_;
    }
    return io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
  }

  public static final int ARTIFACT_UPDATE_FIELD_NUMBER = 4;
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   * @return Whether the artifactUpdate field is set.
   */
  @java.lang.Override
  public boolean hasArtifactUpdate() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   * @return The artifactUpdate.
   */
  @java.lang.Override
  public io.a2a.grpc.TaskArtifactUpdateEvent getArtifactUpdate() {
    if (payloadCase_ == 4) {
       return (io.a2a.grpc.TaskArtifactUpdateEvent) payload_;
    }
    return io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
  }
  /**
   * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
   */
  @java.lang.Override
  public io.a2a.grpc.TaskArtifactUpdateEventOrBuilder getArtifactUpdateOrBuilder() {
    if (payloadCase_ == 4) {
       return (io.a2a.grpc.TaskArtifactUpdateEvent) payload_;
    }
    return io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (payloadCase_ == 1) {
      output.writeMessage(1, (io.a2a.grpc.Task) payload_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (io.a2a.grpc.Message) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (io.a2a.grpc.TaskStatusUpdateEvent) payload_);
    }
    if (payloadCase_ == 4) {
      output.writeMessage(4, (io.a2a.grpc.TaskArtifactUpdateEvent) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (payloadCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (io.a2a.grpc.Task) payload_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.a2a.grpc.Message) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.a2a.grpc.TaskStatusUpdateEvent) payload_);
    }
    if (payloadCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.a2a.grpc.TaskArtifactUpdateEvent) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.a2a.grpc.StreamResponse)) {
      return super.equals(obj);
    }
    io.a2a.grpc.StreamResponse other = (io.a2a.grpc.StreamResponse) obj;

    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1:
        if (!getTask()
            .equals(other.getTask())) return false;
        break;
      case 2:
        if (!getMsg()
            .equals(other.getMsg())) return false;
        break;
      case 3:
        if (!getStatusUpdate()
            .equals(other.getStatusUpdate())) return false;
        break;
      case 4:
        if (!getArtifactUpdate()
            .equals(other.getArtifactUpdate())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (payloadCase_) {
      case 1:
        hash = (37 * hash) + TASK_FIELD_NUMBER;
        hash = (53 * hash) + getTask().hashCode();
        break;
      case 2:
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        break;
      case 3:
        hash = (37 * hash) + STATUS_UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getStatusUpdate().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ARTIFACT_UPDATE_FIELD_NUMBER;
        hash = (53 * hash) + getArtifactUpdate().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.a2a.grpc.StreamResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.a2a.grpc.StreamResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.a2a.grpc.StreamResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.a2a.grpc.StreamResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.a2a.grpc.StreamResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The stream response for a message. The stream should be one of the following
   * sequences:
   * If the response is a message, the stream should contain one, and only one,
   * message and then close
   * If the response is a task lifecycle, the first response should be a Task
   * object followed by zero or more TaskStatusUpdateEvents and
   * TaskArtifactUpdateEvents. The stream should complete when the Task
   * if in an interrupted or terminal state. A stream that ends before these
   * conditions are met are
   * </pre>
   *
   * Protobuf type {@code a2a.v1.StreamResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:a2a.v1.StreamResponse)
      io.a2a.grpc.StreamResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_StreamResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_StreamResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.a2a.grpc.StreamResponse.class, io.a2a.grpc.StreamResponse.Builder.class);
    }

    // Construct using io.a2a.grpc.StreamResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (taskBuilder_ != null) {
        taskBuilder_.clear();
      }
      if (msgBuilder_ != null) {
        msgBuilder_.clear();
      }
      if (statusUpdateBuilder_ != null) {
        statusUpdateBuilder_.clear();
      }
      if (artifactUpdateBuilder_ != null) {
        artifactUpdateBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.a2a.grpc.A2A.internal_static_a2a_v1_StreamResponse_descriptor;
    }

    @java.lang.Override
    public io.a2a.grpc.StreamResponse getDefaultInstanceForType() {
      return io.a2a.grpc.StreamResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.a2a.grpc.StreamResponse build() {
      io.a2a.grpc.StreamResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.a2a.grpc.StreamResponse buildPartial() {
      io.a2a.grpc.StreamResponse result = new io.a2a.grpc.StreamResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(io.a2a.grpc.StreamResponse result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(io.a2a.grpc.StreamResponse result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1 &&
          taskBuilder_ != null) {
        result.payload_ = taskBuilder_.build();
      }
      if (payloadCase_ == 2 &&
          msgBuilder_ != null) {
        result.payload_ = msgBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          statusUpdateBuilder_ != null) {
        result.payload_ = statusUpdateBuilder_.build();
      }
      if (payloadCase_ == 4 &&
          artifactUpdateBuilder_ != null) {
        result.payload_ = artifactUpdateBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.a2a.grpc.StreamResponse) {
        return mergeFrom((io.a2a.grpc.StreamResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.a2a.grpc.StreamResponse other) {
      if (other == io.a2a.grpc.StreamResponse.getDefaultInstance()) return this;
      switch (other.getPayloadCase()) {
        case TASK: {
          mergeTask(other.getTask());
          break;
        }
        case MSG: {
          mergeMsg(other.getMsg());
          break;
        }
        case STATUS_UPDATE: {
          mergeStatusUpdate(other.getStatusUpdate());
          break;
        }
        case ARTIFACT_UPDATE: {
          mergeArtifactUpdate(other.getArtifactUpdate());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetTaskFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetMsgFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetStatusUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetArtifactUpdateFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder> taskBuilder_;
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     * @return Whether the task field is set.
     */
    @java.lang.Override
    public boolean hasTask() {
      return payloadCase_ == 1;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     * @return The task.
     */
    @java.lang.Override
    public io.a2a.grpc.Task getTask() {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1) {
          return (io.a2a.grpc.Task) payload_;
        }
        return io.a2a.grpc.Task.getDefaultInstance();
      } else {
        if (payloadCase_ == 1) {
          return taskBuilder_.getMessage();
        }
        return io.a2a.grpc.Task.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder setTask(io.a2a.grpc.Task value) {
      if (taskBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        taskBuilder_.setMessage(value);
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder setTask(
        io.a2a.grpc.Task.Builder builderForValue) {
      if (taskBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        taskBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder mergeTask(io.a2a.grpc.Task value) {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1 &&
            payload_ != io.a2a.grpc.Task.getDefaultInstance()) {
          payload_ = io.a2a.grpc.Task.newBuilder((io.a2a.grpc.Task) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1) {
          taskBuilder_.mergeFrom(value);
        } else {
          taskBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1;
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public Builder clearTask() {
      if (taskBuilder_ == null) {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1) {
          payloadCase_ = 0;
          payload_ = null;
        }
        taskBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    public io.a2a.grpc.Task.Builder getTaskBuilder() {
      return internalGetTaskFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.TaskOrBuilder getTaskOrBuilder() {
      if ((payloadCase_ == 1) && (taskBuilder_ != null)) {
        return taskBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1) {
          return (io.a2a.grpc.Task) payload_;
        }
        return io.a2a.grpc.Task.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Task task = 1 [json_name = "task"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder> 
        internalGetTaskFieldBuilder() {
      if (taskBuilder_ == null) {
        if (!(payloadCase_ == 1)) {
          payload_ = io.a2a.grpc.Task.getDefaultInstance();
        }
        taskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.Task, io.a2a.grpc.Task.Builder, io.a2a.grpc.TaskOrBuilder>(
                (io.a2a.grpc.Task) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1;
      onChanged();
      return taskBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.Message, io.a2a.grpc.Message.Builder, io.a2a.grpc.MessageOrBuilder> msgBuilder_;
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     * @return The msg.
     */
    @java.lang.Override
    public io.a2a.grpc.Message getMsg() {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (io.a2a.grpc.Message) payload_;
        }
        return io.a2a.grpc.Message.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return msgBuilder_.getMessage();
        }
        return io.a2a.grpc.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder setMsg(io.a2a.grpc.Message value) {
      if (msgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        msgBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder setMsg(
        io.a2a.grpc.Message.Builder builderForValue) {
      if (msgBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        msgBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder mergeMsg(io.a2a.grpc.Message value) {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != io.a2a.grpc.Message.getDefaultInstance()) {
          payload_ = io.a2a.grpc.Message.newBuilder((io.a2a.grpc.Message) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          msgBuilder_.mergeFrom(value);
        } else {
          msgBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public Builder clearMsg() {
      if (msgBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        msgBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    public io.a2a.grpc.Message.Builder getMsgBuilder() {
      return internalGetMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.MessageOrBuilder getMsgOrBuilder() {
      if ((payloadCase_ == 2) && (msgBuilder_ != null)) {
        return msgBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (io.a2a.grpc.Message) payload_;
        }
        return io.a2a.grpc.Message.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.Message msg = 2 [json_name = "message"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.Message, io.a2a.grpc.Message.Builder, io.a2a.grpc.MessageOrBuilder> 
        internalGetMsgFieldBuilder() {
      if (msgBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = io.a2a.grpc.Message.getDefaultInstance();
        }
        msgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.Message, io.a2a.grpc.Message.Builder, io.a2a.grpc.MessageOrBuilder>(
                (io.a2a.grpc.Message) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return msgBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.TaskStatusUpdateEvent, io.a2a.grpc.TaskStatusUpdateEvent.Builder, io.a2a.grpc.TaskStatusUpdateEventOrBuilder> statusUpdateBuilder_;
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     * @return Whether the statusUpdate field is set.
     */
    @java.lang.Override
    public boolean hasStatusUpdate() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     * @return The statusUpdate.
     */
    @java.lang.Override
    public io.a2a.grpc.TaskStatusUpdateEvent getStatusUpdate() {
      if (statusUpdateBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (io.a2a.grpc.TaskStatusUpdateEvent) payload_;
        }
        return io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return statusUpdateBuilder_.getMessage();
        }
        return io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    public Builder setStatusUpdate(io.a2a.grpc.TaskStatusUpdateEvent value) {
      if (statusUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        statusUpdateBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    public Builder setStatusUpdate(
        io.a2a.grpc.TaskStatusUpdateEvent.Builder builderForValue) {
      if (statusUpdateBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        statusUpdateBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    public Builder mergeStatusUpdate(io.a2a.grpc.TaskStatusUpdateEvent value) {
      if (statusUpdateBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance()) {
          payload_ = io.a2a.grpc.TaskStatusUpdateEvent.newBuilder((io.a2a.grpc.TaskStatusUpdateEvent) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          statusUpdateBuilder_.mergeFrom(value);
        } else {
          statusUpdateBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    public Builder clearStatusUpdate() {
      if (statusUpdateBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        statusUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    public io.a2a.grpc.TaskStatusUpdateEvent.Builder getStatusUpdateBuilder() {
      return internalGetStatusUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.TaskStatusUpdateEventOrBuilder getStatusUpdateOrBuilder() {
      if ((payloadCase_ == 3) && (statusUpdateBuilder_ != null)) {
        return statusUpdateBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (io.a2a.grpc.TaskStatusUpdateEvent) payload_;
        }
        return io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.TaskStatusUpdateEvent status_update = 3 [json_name = "statusUpdate"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.TaskStatusUpdateEvent, io.a2a.grpc.TaskStatusUpdateEvent.Builder, io.a2a.grpc.TaskStatusUpdateEventOrBuilder> 
        internalGetStatusUpdateFieldBuilder() {
      if (statusUpdateBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = io.a2a.grpc.TaskStatusUpdateEvent.getDefaultInstance();
        }
        statusUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.TaskStatusUpdateEvent, io.a2a.grpc.TaskStatusUpdateEvent.Builder, io.a2a.grpc.TaskStatusUpdateEventOrBuilder>(
                (io.a2a.grpc.TaskStatusUpdateEvent) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return statusUpdateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.TaskArtifactUpdateEvent, io.a2a.grpc.TaskArtifactUpdateEvent.Builder, io.a2a.grpc.TaskArtifactUpdateEventOrBuilder> artifactUpdateBuilder_;
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     * @return Whether the artifactUpdate field is set.
     */
    @java.lang.Override
    public boolean hasArtifactUpdate() {
      return payloadCase_ == 4;
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     * @return The artifactUpdate.
     */
    @java.lang.Override
    public io.a2a.grpc.TaskArtifactUpdateEvent getArtifactUpdate() {
      if (artifactUpdateBuilder_ == null) {
        if (payloadCase_ == 4) {
          return (io.a2a.grpc.TaskArtifactUpdateEvent) payload_;
        }
        return io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
      } else {
        if (payloadCase_ == 4) {
          return artifactUpdateBuilder_.getMessage();
        }
        return io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    public Builder setArtifactUpdate(io.a2a.grpc.TaskArtifactUpdateEvent value) {
      if (artifactUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        artifactUpdateBuilder_.setMessage(value);
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    public Builder setArtifactUpdate(
        io.a2a.grpc.TaskArtifactUpdateEvent.Builder builderForValue) {
      if (artifactUpdateBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        artifactUpdateBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    public Builder mergeArtifactUpdate(io.a2a.grpc.TaskArtifactUpdateEvent value) {
      if (artifactUpdateBuilder_ == null) {
        if (payloadCase_ == 4 &&
            payload_ != io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance()) {
          payload_ = io.a2a.grpc.TaskArtifactUpdateEvent.newBuilder((io.a2a.grpc.TaskArtifactUpdateEvent) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 4) {
          artifactUpdateBuilder_.mergeFrom(value);
        } else {
          artifactUpdateBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 4;
      return this;
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    public Builder clearArtifactUpdate() {
      if (artifactUpdateBuilder_ == null) {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 4) {
          payloadCase_ = 0;
          payload_ = null;
        }
        artifactUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    public io.a2a.grpc.TaskArtifactUpdateEvent.Builder getArtifactUpdateBuilder() {
      return internalGetArtifactUpdateFieldBuilder().getBuilder();
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    @java.lang.Override
    public io.a2a.grpc.TaskArtifactUpdateEventOrBuilder getArtifactUpdateOrBuilder() {
      if ((payloadCase_ == 4) && (artifactUpdateBuilder_ != null)) {
        return artifactUpdateBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 4) {
          return (io.a2a.grpc.TaskArtifactUpdateEvent) payload_;
        }
        return io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
      }
    }
    /**
     * <code>.a2a.v1.TaskArtifactUpdateEvent artifact_update = 4 [json_name = "artifactUpdate"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.a2a.grpc.TaskArtifactUpdateEvent, io.a2a.grpc.TaskArtifactUpdateEvent.Builder, io.a2a.grpc.TaskArtifactUpdateEventOrBuilder> 
        internalGetArtifactUpdateFieldBuilder() {
      if (artifactUpdateBuilder_ == null) {
        if (!(payloadCase_ == 4)) {
          payload_ = io.a2a.grpc.TaskArtifactUpdateEvent.getDefaultInstance();
        }
        artifactUpdateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.a2a.grpc.TaskArtifactUpdateEvent, io.a2a.grpc.TaskArtifactUpdateEvent.Builder, io.a2a.grpc.TaskArtifactUpdateEventOrBuilder>(
                (io.a2a.grpc.TaskArtifactUpdateEvent) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 4;
      onChanged();
      return artifactUpdateBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:a2a.v1.StreamResponse)
  }

  // @@protoc_insertion_point(class_scope:a2a.v1.StreamResponse)
  private static final io.a2a.grpc.StreamResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.a2a.grpc.StreamResponse();
  }

  public static io.a2a.grpc.StreamResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamResponse>
      PARSER = new com.google.protobuf.AbstractParser<StreamResponse>() {
    @java.lang.Override
    public StreamResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StreamResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.a2a.grpc.StreamResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

