// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: a2a.proto
// Protobuf Java Version: 4.31.1

package io.a2a.grpc;

@com.google.protobuf.Generated
public interface TaskPushNotificationConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:a2a.v1.TaskPushNotificationConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name=tasks/{id}/pushNotificationConfigs/{id}
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name=tasks/{id}/pushNotificationConfigs/{id}
   * </pre>
   *
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2 [json_name = "pushNotificationConfig"];</code>
   * @return Whether the pushNotificationConfig field is set.
   */
  boolean hasPushNotificationConfig();
  /**
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2 [json_name = "pushNotificationConfig"];</code>
   * @return The pushNotificationConfig.
   */
  io.a2a.grpc.PushNotificationConfig getPushNotificationConfig();
  /**
   * <code>.a2a.v1.PushNotificationConfig push_notification_config = 2 [json_name = "pushNotificationConfig"];</code>
   */
  io.a2a.grpc.PushNotificationConfigOrBuilder getPushNotificationConfigOrBuilder();
}
